### ISSUE TITLE
Firefox 81 Nightly - Opening a Google Sheet causes memory leak and failure to open

### ISSUE THREAD

**Issue by DoulosTrieste** [kkapsner/CanvasBlocker#497] opened 2020-07-29 14:09 UTC
## Description
Opening a Google spreadsheet in a Firefox window.

## Expected Behavior
Spreadsheet loads normally. Memory usage is normal.

## Current Behavior
Sheet fails to load while Firefox throws a warning about a slow addon. Pressing Stop or Temporarily Disble does not allow the sheet to load successfully. Memory usage grows, reaching an observed peak of 5 GB for that process alone.

## Steps to Reproduce (for bugs)
The APIs being blocked are DOM and Canvas, with the first simple preset being used, together with the RECAPTCHA whitelist preset. A small modification made to the used preset by setting persistent mode to 2 weeks.

## Context
Fresh profile presents normal behaviour.

## Your Environment
CanvasBlocker Version used: 1.3
* Firefox version incl. 32- or 64-bit: Nightly, 81.0a1 (2020-07-28), 64-bit
* Operating System and version (desktop or mobile): Windows 10 Version 2004

* Installed addons: 
Absolute Enable   Right Click & Copy
--
Amazon.com
Auto Tab Discard
Bing
CanvasBlocker
ClearURLs
Cookie AutoDelete
Decentraleyes
Don't touch my tabs! (rel=noopener)
DuckDuckGo
DuckDuckGo Privacy Essentials
eBay
Enhancer for YouTube™
ETag Stoppa
Expire History By Days
F.B Purity - Cleans up Facebook (WX)
Firefox Multi-Account Containers
Firefox Relay
First Party Isolation
Google
HTTPS Everywhere
Image Search Options
Metastream Remote
Nano Defender
Print Edit WE
Privacy Enhanced Mode for Embedded   YouTube
Reddit Enhancement Suite
Redirect AMP to HTML
Save-Data: on
SearchPreview
Select After Closing Current
Share Backported
ShopBack Cashback Button
Simple Tab Groups
Simple Translate
Snowflake
Switch Container Plus
Tab Mix - Links
Terms of Service; Didn’t Read
Text Link
Tracking Protection Toggle
Tracking Token Stripper
Turbo Download Manager (3rd edition)
uBlock Origin
Undo Close Tab
Unseen
Violentmonkey
Wikipedia (en)
Zoom Page WE

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "mail.google.com",
			"protectDOMRect": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"protectWindow": true,
		"allowWindowNameInFrames": true,
		"section_notifications": true,
		"blockMode": false
	},
	"displayHiddenSettings": true,
	"whiteList": "docs.google.com",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": 
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 2,
	"persistentRndClearIntervalUnit": "weeks",
	"lastPersistentRndClearing": 0,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "29",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment] 2020-07-29 19:42
I'm not able to reproduce your problem with your settings. Please check with a fresh profile and only CB installed (with your settings). It might be another extension that does not play well with CB.

**Comment by kkapsner** [comment] 2020-08-24 22:07
What is the result with a fresh profile and only CB?

**Comment by kkapsner** [comment] 2020-10-06 13:35
More than one month without answer. So I assume the problem is solved somehow and I will close this issue. If it still exists please provide the necessary information and I will reopen this issue.

**Closed by kkapsner** 2020-10-06 13:35 UTC
