### ISSUE TITLE
textMetrics on Reddit causes bold titles to not display correctly (see pictures on "Context")

### ISSUE THREAD

**Issue by llnngg** [kkapsner/CanvasBlocker#629] opened 2022-10-05 15:05 UTC
## Description
I've been using CB on Reddit for quite some time and for a few days now I've noticed that the textMetricts notification is trigered, but only when I'm logged in and mainly in my HomeFeed and post that I access from my HomeFeed.

## Expected Behavior
Bold titles should be displayed properly.

## Current Behavior
Bold headings are displayed incorrectly, in normal font.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
Login on your reddit account an go to your homefeed. Do you must have domrect and tectmetricts activated.

## Context
https://ibb.co/6Xt3L56
https://ibb.co/x7frkDw

## Your Environment
CB 1.8
Windows 64 bits

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "mail.google.com",
			"protectDOMRect": false
		},
		{
			"url": "onedrive.live.com",
			"protectDOMRect": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "null",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "null",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 1,
	"persistentRndClearIntervalUnit": "weeks",
	"lastPersistentRndClearing": 1664982018638,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "3",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": false,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment] 2023-03-14 19:44
Sorry for the late response.

I'm currently not able to register for reddit - so no idea what's going on there.

BUT if you are already logged in at reddit they already have the best fingerprint for you: your username and credentials. So I would simply whitelist reddit for these APIs.

**Comment by spodermenpls** [comment] 2023-03-15 04:30
I am a Reddit user as well, using the site logged-in and logged-out, and can't reproduce the described issues today (textMetrics doesn't get called anymore, as it seems). I do remember regular issues with certain optical features (also maybe due to me using LocalCDN and it injecting Google Material Icons and Google Fonts on my setup from cache), but never put too much emphasis on those, since they never hindered any actual usage of the site.

**Comment by kkapsner** [comment] 2023-03-25 10:43
@spodermenpls: thanks for the information. Then I will close this issue.

**Closed by kkapsner** 2023-03-25 10:43 UTC
