### ISSUE TITLE
cdnjs.com very poor performance in conjunction with Firefox

### ISSUE THREAD

**Issue by heydojo** [kkapsner/CanvasBlocker#430] opened 2020-01-19 00:16 UTC
## Description
Please visit https://cdnjs.com using Firefox browser with the CanvasBlocker extension installed. The browser will take a long time to load the page fully and then complain that CanvasBlocker is causing a performance hit. It then offers to temporarily disable the extension.

## Expected Behavior
CanvasBlocker does not cause a performance hit and need to be disabled.

## Current Behavior
CanvasBlocker does cause a performance hit and needs to be disabled for the whole site to properly finish rendering.

## Possible Solution
No clues, unfortunately.

## Steps to Reproduce (for bugs)

1. Open Firefox browser
2. Ensure that the CanvasBlocker extension is installed
3. Visit https://cdnjs.com
4. Wait for the page to load and the browser error messages to appear

## Your Environment

* CanvasBlocker Version used: 0.5.14
* Firefox version 72.0.1 (64-bit)
* Operating System Win 10 Pro (Desktop)

## Your Settings

```json
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1579392279047,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "3",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}",
		"firefoxVersion": "{real Firefox version}",
		"appVersion": "5.0 ({windowManager})",
		"buildID": "20181001000000",
		"productSub": "20100101",
		"userAgent": "Mozilla/5.0 ({platformDetails}; rv:{firefoxVersion}) Gecko/20100101 Firefox/{firefoxVersion}"
	},
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}
```

**Comment by kkapsner** [comment] 2020-01-19 00:44
Unfortunately I'm not able to reproduce your problem. Please try if version 1.0 (released yesterday) helps.

**Comment by heydojo** [comment] 2020-01-23 15:53
Thanks @kkapsner

The extension was automatically updated to 1.0 and unfortunately I still see the same result.

![cdnjs](https://user-images.githubusercontent.com/186629/72999708-a7397b00-3df7-11ea-8608-a4651ed0cf6a.png)

https://cdnjs.com/ is the only site this happens on and disabling CanvasBlocker is the only way to resolve the issue thus far.

I guess it could be a conflict with another addon. Temporary Containers being the first suspect.

**Comment by geeknik** [comment] 2020-01-23 16:09
I'm using TC + CanvasBlocker with Firefox Nighty (v74.0a1) on Fedora 31 and I'm not seeing any issues on cdnjs.com.

**Comment by kkapsner** [comment] 2020-01-23 16:55
Does whitelisting cdnjs.com help?
Which other extensions do you have installed?

**Comment by kkapsner** [comment] 2020-02-09 22:51
@heydojo: As I'm not able to reproduce the problem I need your help to resolve this issue for you. So please answer my questions.

**Comment by kkapsner** [comment] 2020-02-24 22:40
No answer to my questions for more than a month: I will close this issue.
If you still encounter this problem and provide the needed information I can reopen it.

**Closed by kkapsner** 2020-02-24 22:40 UTC
