### ISSUE TITLE
Screen size spoofing

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#404] opened 2019-10-22 16:10 UTC
https://addons.mozilla.org/en-GB/firefox/addon/chameleon-ext/

It feels like this addon does everything CanvasBlocker does, just a little worse ... except screen size spoofing - do you think you could add it in?

**Comment by crssi** [comment] 2019-10-22 17:38
Screen size cannot be spoofed without getting busted.
The only way is using RFP (`privacy.resistFingerprinting`)

**Comment by kkapsner** [comment] 2019-10-22 19:11
This is a duplicate of #220

**Closed by kkapsner** 2019-10-22 19:11 UTC
Labels: duplicate
