### ISSUE TITLE
Setting's descriptions with dark theme.

### ISSUE THREAD

**Issue by tr37ion** [kkapsner/CanvasBlocker#181] opened 2018-02-22 22:42 UTC
Switching descriptions on with dark theme uses white font colour if used with dark theme.

![image](https://user-images.githubusercontent.com/1538617/36568369-a16b2c62-1821-11e8-87d3-5301377ebe91.png)

**Comment by kkapsner** [comment] 2018-02-22 23:53
Which OS are you on? And which Firefox version? I'm not able to see this problem on my side.

**Comment by kkapsner** [comment] 2018-03-22 18:56
Without further informations to reproduce the problem I'm not able to go on with this issue. Therefore I will close it. If you provide further details and the issue still persists you can reopen the issue.

**Comment by rugk** [comment] 2019-04-27 15:27
I can reproduce that if:
1. Use Firefox 68.
2. Set your _system_ to dark mode.
3. Start Firefox.
4. Set your system to light mode again.

What happens:
Firefox keeps styling for input fields from the start on. (likely because it is some system-specific thing.)
Only the other parts of the styling are reset.

GNOME
Fedora 29

***Arrgh** even worse:
* If I then however over the settings, they take the "correct" design, i.e. in my case light.
  (this only works in about:addons, not a new tab)
* Obviously, it does not work if the settings are opened in a new tab. There it always uses the "light" design,

---


This is reproducible because of , but I guess the OP actually used a Firefox version that did not have the `prefers-color-scheme` setting. As such, there the input fields likely were dark anyway, because of a system setting.

**Comment by kkapsner** [comment] 2019-04-29 14:30
Well... the settings page looks horrible with a dark system theme despite the Firefox bug.

I will just use the theme parameter in the options page as well.

**Closed** 2019-05-02 21:51 UTC
Labels: enhancement

**Comment by kkapsner** [comment] 2019-05-11 11:24
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment] 2019-05-26 17:36
Release 0.5.9 is published.
