### ISSUE TITLE
Can't load Router Interface (Fritzbox)

### ISSUE THREAD

**Issue by MysteryIII** [kkapsner/CanvasBlocker#602] opened 2022-03-24 11:25 UTC
The Web Interface of my Router (Fritzbox) can't be loaded while Canvas Blocker is active.

## Description
I open the Interface with the IP address, but it suddenly stopped working. I already had local IPs whitelisted for everything but added the Router IP just to make sure.
The icon of Canvas Blocker is green, so it also indicates that the site is whitelisted, but still it won't load, until I completely deactivate the Add-on.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Fx 98, Win 10: x64
Canvas Blocker 1.8

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "shoop.de",
			"protectDOMRect": false,
			"fakeMinimalScreenSize": false,
			"blockMode": "allowEverything",
			"protectWindow": false,
			"protectAudio": false,
			"useAudioCache": false,
			"allowWindowNameInFrames": true,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false,
			"protectedCanvasPart": "nothing",
			"historyLengthThreshold": 8
		},
		{
			"url": "192.168.0.*",
			"blockMode": "allowEverything",
			"protectWindow": false,
			"protectDOMRect": false,
			"protectAudio": false,
			"useAudioCache": false,
			"allowWindowNameInFrames": true,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false,
			"protectedCanvasPart": "nothing",
			"historyLengthThreshold": 8
		},
		{
			"url": "192.168.0.40",
			"blockMode": "allowEverything",
			"protectWindow": false,
			"protectDOMRect": false,
			"protectAudio": false,
			"useAudioCache": false,
			"allowWindowNameInFrames": true,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false,
			"protectedCanvasPart": "nothing",
			"historyLengthThreshold": 8
		},
		{
			"url": "paypal.com",
			"protectNavigator": false,
			"protectWindow": false,
			"protectDOMRect": false,
			"protectAudio": false,
			"useAudioCache": false,
			"allowWindowNameInFrames": true,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false,
			"blockMode": "allowEverything",
			"protectedCanvasPart": "nothing",
			"historyLengthThreshold": 8
		},
		{
			"url": "*.paypal.com",
			"blockMode": "allowEverything",
			"protectedCanvasPart": "nothing",
			"protectAudio": false,
			"useAudioCache": false,
			"historyLengthThreshold": 8,
			"protectWindow": false,
			"protectDOMRect": false,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false
		},
		{
			"url": "192.168.0.1",
			"blockMode": "allowEverything",
			"protectedCanvasPart": "nothing",
			"protectAudio": false,
			"useAudioCache": false,
			"historyLengthThreshold": 8,
			"protectWindow": false,
			"protectDOMRect": false,
			"protectTextMetrics": false,
			"protectScreen": false,
			"blockDataURLs": false
		}
	],
	"hiddenSettings": {
		"audioFakeRate": false,
		"webGLVendor": false,
		"enableStackList": false
	},
	"expandStatus": {
		"protectNavigator": true,
		"blockMode": true,
		"allowWindowNameInFrames": true,
		"protectDOMRect": true,
		"section_DOMRect-API": true,
		"protectScreen": true,
		"showNotifications": true,
		"section_History-API": true,
		"fakeMinimalScreenSize": true,
		"section_Canvas-API": true,
		"section_Audio-API": true,
		"protectWindow": true,
		"protectAudio": true,
		"protectedCanvasPart": true,
		"useAudioCache": true,
		"historyLengthThreshold": true,
		"protectTextMetrics": true,
		"screenSize": true,
		"highlightPageAction": true,
		"highlightBrowserAction": true,
		"blockDataURLs": true
	},
	"displayHiddenSettings": true,
	"whiteList": "shoop.de,paypal.com,*.paypal.com,192.168.0.1,192.168.0.*",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 10,
	"maxFakeSize": 1000000,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{\"firefox-container-4@www.mydealz.de\":[124,87,155,214,69,167,73,58,53,174,30,233,177,121,82,213,124,52,75,254,19,177,75,192,66,223,167,121,243,104,187,35,151,101,169,59,30,186,124,39,124,155,185,101,89,196,57,97,232,21,188,57,177,40,202,251,126,249,230,168,217,221,62,153,36,111,143,224,90,87,62,213,246,218,34,150,54,14,253,139,73,246,192,59,167,34,53,111,157,128,41,39,18,211,162,35,54,225,42,42,78,106,48,58,186,99,208,137,76,22,146,210,182,92,143,180,187,92,148,229,218,253,172,93,9,53,12,55],\"firefox-container-1@www.netvibes.com\":[103,184,145,153,146,150,14,93,154,48,118,221,228,53,123,67,190,218,161,30,142,78,215,123,177,204,36,30,48,98,185,100,229,254,56,210,146,35,133,59,40,246,212,139,36,192,157,137,249,56,23,75,165,236,95,186,210,121,108,128,54,57,22,249,255,154,112,201,87,175,189,30,225,161,223,179,194,115,208,250,118,28,200,32,242,183,242,167,37,228,245,171,132,136,47,27,225,171,34,189,126,133,117,120,235,159,202,159,25,109,164,92,104,118,178,140,15,15,198,248,201,120,96,120,225,223,109,62],\"firefox-container-15390@www.google.com\":[94,201,207,227,235,138,104,183,255,73,83,193,34,5,22,179,116,82,207,195,211,140,69,4,43,237,12,6,72,222,201,86,120,185,47,51,61,222,131,237,130,126,204,202,210,137,55,171,243,218,12,151,22,125,196,6,27,18,202,229,109,42,177,226,94,10,144,24,36,206,103,95,85,148,146,5,104,228,235,211,209,221,90,119,132,92,126,216,45,102,198,101,3,187,186,213,47,151,118,12,135,93,100,135,235,163,47,90,170,204,140,145,39,123,96,170,133,31,88,223,243,90,250,92,251,131,176,171],\"firefox-container-15391@durchlauferhitzer-ratgeber.de\":[131,219,83,236,30,164,155,78,140,186,40,72,50,32,166,4,83,44,70,172,177,33,68,174,63,192,199,203,33,161,16,54,173,148,197,124,169,108,169,144,109,153,111,167,9,167,210,20,155,217,100,248,143,30,201,237,26,170,9,204,95,175,186,132,220,250,214,129,48,249,9,21,182,42,70,252,127,172,153,185,140,237,226,84,134,73,200,144,122,78,169,233,206,78,182,73,241,182,228,110,132,18,141,117,217,247,116,65,82,56,169,228,74,15,188,20,49,100,243,66,210,231,54,73,51,238,183,149],\"firefox-container-15392@www.google.com\":[65,212,64,91,134,39,59,95,120,137,113,228,98,50,212,112,156,70,233,223,239,156,144,164,77,107,123,58,128,39,229,125,206,33,38,60,127,47,90,129,225,112,173,206,198,122,7,72,11,86,30,117,234,64,143,204,215,57,252,190,63,138,155,11,69,121,119,216,93,39,168,31,64,82,117,182,8,70,179,234,196,117,225,24,170,223,237,9,204,101,141,131,60,178,192,92,113,206,14,133,67,106,88,131,21,107,111,60,54,100,56,200,80,229,174,191,16,97,68,105,91,138,179,170,145,226,62,219],\"firefox-container-15393@www.youtube.com\":[113,80,114,128,0,200,30,44,14,211,131,37,141,73,100,104,151,41,54,251,141,46,5,107,53,157,110,218,238,106,118,158,118,113,54,155,200,216,159,195,30,211,66,73,148,58,108,112,250,159,38,170,151,86,25,70,164,252,46,168,1,124,36,172,23,36,43,134,84,100,156,235,96,192,181,122,229,63,190,22,73,1,120,132,102,96,218,38,73,202,186,219,126,86,217,209,221,79,55,229,206,63,37,99,137,216,206,114,8,182,5,53,80,34,218,217,66,149,66,14,35,58,236,217,123,29,142,6],\"firefox-container-15394@www.google.com\":[38,202,70,230,150,174,255,150,8,9,10,233,134,61,143,55,77,3,106,59,177,16,108,221,20,113,142,33,175,204,66,212,126,125,48,250,242,125,42,66,21,96,120,16,175,80,176,127,63,178,134,10,172,119,197,103,1,236,208,68,232,232,78,0,180,192,159,134,194,184,60,79,145,62,113,36,211,49,70,226,178,18,33,236,152,102,90,125,64,3,18,95,97,9,73,53,63,79,251,131,86,182,106,45,206,187,211,124,163,163,74,129,152,91,164,103,184,61,147,95,111,226,174,56,194,240,149,60],\"firefox-container-15395@www.elektrikshop.de\":[107,1,131,111,126,27,115,185,138,251,94,26,33,97,165,117,67,96,242,151,27,184,229,157,223,0,34,235,90,32,70,92,113,255,20,126,89,152,212,82,176,1,85,83,237,227,31,246,65,243,213,75,179,246,196,131,59,62,199,131,248,91,190,241,173,168,72,188,48,212,32,174,4,93,218,122,61,166,157,39,195,127,200,84,88,47,101,151,103,98,164,44,124,247,195,94,100,87,182,78,39,231,247,224,163,122,144,96,146,82,185,5,237,129,246,228,167,69,30,192,94,65,96,176,37,153,139,70],\"firefox-container-15396@www.google.com\":[211,22,127,153,194,181,136,3,175,44,101,171,91,218,30,188,163,254,223,98,106,118,188,164,190,198,58,226,203,88,6,86,200,12,43,232,43,55,113,224,74,91,62,0,103,234,80,159,0,190,242,94,135,54,149,210,16,123,226,141,19,3,241,150,133,18,248,192,25,110,87,236,254,26,67,61,167,3,10,115,183,248,112,74,173,208,218,125,226,201,180,175,38,212,49,124,55,132,166,31,111,155,123,60,100,103,194,202,99,169,91,191,213,114,129,13,124,147,192,20,209,119,122,84,121,11,182,22],\"firefox-container-15390@ogs.google.com\":[74,115,190,169,17,82,173,232,220,232,37,163,153,37,193,129,111,244,64,103,103,230,44,32,199,11,178,176,14,106,154,105,255,26,194,24,201,82,127,37,190,63,37,81,188,84,113,22,216,161,111,58,104,128,107,147,178,78,232,252,217,163,39,56,205,113,68,180,55,229,26,217,37,136,69,164,141,187,198,212,128,101,2,39,246,150,64,195,70,227,70,185,218,34,141,124,185,30,225,239,212,169,22,54,169,18,215,232,81,90,175,200,80,175,149,125,241,85,64,234,193,173,171,61,200,121,175,27],\"firefox-container-15398@www.findedeindurchlauferhitzer.de\":[122,63,127,0,20,31,103,241,222,127,39,80,41,165,221,168,9,163,188,57,19,179,2,85,134,49,210,174,243,111,115,12,248,207,113,26,249,162,207,244,134,23,129,193,83,81,225,26,9,115,44,148,238,193,206,27,4,136,74,192,145,94,139,105,91,229,105,72,49,69,17,173,115,103,167,235,20,19,107,131,145,8,50,151,47,245,127,195,32,236,236,38,136,235,30,50,104,23,152,24,186,252,164,209,48,128,113,15,221,78,239,63,112,54,46,20,11,94,207,66,231,145,11,158,8,22,17,196],\"firefox-container-4@www.idealo.de\":[29,223,79,90,58,98,19,135,197,247,183,83,105,85,150,248,182,94,215,194,227,201,234,224,252,75,184,12,12,134,143,135,29,205,123,184,232,248,104,113,239,31,254,236,130,246,197,129,178,151,42,107,221,237,90,55,117,216,176,57,194,26,71,48,210,40,67,140,34,206,223,16,43,47,37,26,80,53,16,179,94,29,20,85,228,59,118,23,119,146,144,128,27,69,119,180,58,159,250,211,79,43,230,118,26,8,225,158,169,17,186,66,97,17,55,50,244,125,159,217,110,22,67,29,147,200,229,205],\"firefox-container-4@www.google.com\":[9,196,155,127,36,75,14,72,220,127,110,169,209,155,190,32,3,205,101,100,230,117,33,210,198,29,38,30,1,248,109,196,23,233,119,31,18,99,190,35,222,45,10,220,210,233,135,97,235,41,117,191,28,196,251,232,139,221,14,132,229,190,235,6,216,113,44,61,205,19,172,194,40,243,78,123,183,139,157,86,173,250,254,77,230,42,251,60,215,60,10,226,148,61,62,94,84,161,157,234,1,236,3,86,55,224,240,228,26,100,7,203,18,176,84,232,182,213,86,248,87,191,231,221,53,111,246,11],\"firefox-container-15400@www.stiebel-eltron.de\":[116,145,217,187,245,30,61,145,251,34,244,24,227,177,5,160,73,80,160,224,79,45,252,107,40,90,72,56,224,202,86,174,246,253,242,49,132,40,20,193,244,229,91,250,33,254,197,60,34,164,117,155,208,23,79,67,88,43,230,195,82,108,115,162,26,144,65,112,236,150,22,47,128,156,223,126,99,151,89,220,110,113,166,60,118,180,109,223,197,201,122,35,125,129,83,18,120,167,48,98,223,233,214,27,6,119,245,40,90,85,175,29,17,129,86,112,62,119,133,109,54,144,78,67,151,63,64,66],\"firefox-container-15403@www.google.com\":[116,252,42,126,83,155,59,40,38,162,175,167,37,245,195,116,253,77,141,254,204,142,211,237,62,43,254,22,134,203,243,163,205,26,43,55,202,121,6,138,93,213,123,59,162,182,12,116,13,169,215,199,41,216,162,78,194,245,110,221,16,202,98,155,20,14,112,128,20,103,13,188,136,98,23,81,63,34,143,69,162,227,229,79,122,160,202,120,89,254,194,11,216,249,192,200,229,246,241,245,55,204,63,78,91,155,190,190,230,255,162,0,178,179,21,226,204,220,91,13,162,227,54,199,168,79,43,230],\"firefox-container-15405@www.google.com\":[119,202,49,242,188,203,166,194,193,43,130,109,127,52,199,3,205,57,88,56,10,175,140,162,89,177,145,209,31,190,200,198,254,9,46,125,250,214,103,45,183,6,16,60,178,212,131,124,178,171,143,186,106,209,195,161,95,101,105,122,204,232,243,240,117,238,124,231,196,134,164,184,10,118,24,225,229,95,70,85,51,175,199,146,218,183,5,145,234,99,220,46,41,15,254,45,6,215,240,79,142,61,170,222,138,70,74,112,62,224,227,16,238,56,59,84,231,220,69,112,91,99,149,144,228,241,237,20],\"firefox-container-15406@www.qnap.com\":[5,225,87,127,171,177,123,159,240,242,178,143,165,14,189,135,66,148,41,157,202,155,187,112,63,41,188,120,33,173,18,124,46,135,121,38,26,176,87,158,25,184,41,249,181,163,220,218,56,26,70,109,195,247,135,79,218,73,87,77,179,168,141,88,180,127,204,86,169,30,86,173,230,145,216,161,119,230,161,235,168,255,55,176,88,242,252,94,101,109,90,44,179,186,85,249,145,51,150,88,1,192,96,187,251,202,174,238,0,201,241,107,31,57,0,58,173,233,154,151,191,211,102,107,169,39,177,130],\"firefox-container-4@www.ebay.de\":[15,37,75,123,197,188,110,152,140,101,75,47,239,30,169,182,136,194,117,223,55,250,36,163,57,141,87,96,3,177,158,28,22,160,213,19,63,20,176,166,195,31,81,25,72,158,148,7,148,190,134,90,214,230,82,76,65,233,52,28,167,44,252,229,136,79,39,22,219,66,241,123,209,138,21,226,132,191,159,138,87,116,102,35,212,40,99,228,203,45,42,124,170,36,22,97,119,118,169,201,62,219,45,200,138,191,124,15,51,225,125,126,92,29,8,53,79,243,184,176,118,38,165,116,188,52,180,253],\"firefox-container-15419@www.reddit.com\":[103,53,218,155,20,210,1,122,30,201,36,122,130,32,116,156,143,93,16,182,69,132,61,99,249,135,219,195,128,244,198,166,214,248,200,149,191,174,116,147,224,247,142,247,183,225,76,128,84,135,81,216,219,130,63,61,78,124,35,206,99,226,62,141,73,7,206,55,159,149,45,155,237,79,186,248,56,8,149,97,141,242,55,239,33,246,15,80,114,192,251,154,166,216,177,154,45,185,153,112,77,66,59,67,9,45,93,208,51,95,94,196,221,122,61,168,141,124,234,174,29,107,214,245,145,224,185,164],\"firefox-container-15420@www.qnap.com\":[249,89,84,141,18,137,242,121,42,231,181,75,91,163,117,74,21,103,158,47,68,16,42,201,34,75,76,79,24,20,217,137,38,131,31,252,59,146,131,209,27,109,77,48,25,255,28,224,35,178,220,131,240,78,250,112,38,1,14,229,30,33,163,88,82,232,1,159,58,47,100,124,124,174,85,185,112,152,165,140,180,5,101,152,224,136,205,29,1,5,109,223,119,135,95,45,105,159,84,33,76,117,193,65,215,86,242,101,3,7,49,241,98,179,174,168,75,93,16,232,231,176,32,205,100,242,171,56],\"firefox-container-15420@www.recaptcha.net\":[249,129,202,244,84,180,148,190,59,220,120,86,204,61,72,232,127,205,57,52,15,195,88,168,216,198,40,63,5,195,248,83,243,96,115,183,148,202,157,72,16,89,105,110,218,208,26,116,232,84,206,26,195,199,124,148,133,3,41,16,209,110,242,18,202,95,155,231,91,254,86,227,69,47,246,174,5,58,166,245,150,137,114,27,70,181,236,255,180,11,31,86,164,61,158,244,222,204,208,216,15,97,223,231,120,233,132,7,77,253,102,48,155,215,164,40,174,177,218,44,57,184,143,71,100,64,232,164],\"firefox-container-15421@www.google.com\":[149,93,75,1,188,55,230,205,221,217,241,76,237,90,246,138,219,33,226,29,200,95,0,148,3,186,32,205,223,6,100,239,27,141,146,27,53,173,23,252,99,175,229,27,90,93,164,155,21,249,164,31,126,46,172,35,183,205,163,122,185,215,214,123,41,228,33,8,71,251,234,167,219,79,106,82,152,234,11,250,115,36,135,211,198,68,217,46,108,117,248,249,25,94,139,54,18,54,57,208,32,199,137,19,27,153,137,9,23,98,173,107,132,78,247,139,218,67,80,156,78,174,240,127,78,143,191,235],\"firefox-container-149@www.qnap.com\":[242,41,242,57,110,59,61,104,12,156,133,240,184,23,69,221,181,247,111,47,240,137,160,233,103,66,2,155,61,52,143,174,189,86,197,35,94,152,65,253,110,138,59,164,217,47,20,250,31,146,250,158,60,173,85,206,108,166,102,32,117,168,195,43,185,124,199,119,174,165,210,167,109,168,25,11,23,0,2,144,34,183,123,251,133,31,155,119,67,39,190,33,184,8,230,78,83,84,72,24,72,241,152,137,5,129,82,60,87,218,33,187,123,130,3,185,148,248,140,71,2,223,185,74,195,35,2,192],\"firefox-container-15427@www.google.com\":[21,127,162,135,218,130,129,140,13,23,196,108,88,204,239,83,15,211,168,146,65,225,141,196,52,65,196,5,184,195,155,216,193,175,149,222,226,142,226,34,55,153,235,27,199,114,78,14,6,6,112,48,1,43,243,191,3,74,184,12,51,178,36,240,63,163,211,231,61,4,221,24,89,206,135,2,86,107,231,92,100,184,219,144,84,86,13,196,172,60,250,120,242,87,139,204,45,236,46,151,245,11,78,206,15,42,3,93,110,34,93,119,162,140,174,147,189,143,4,246,134,233,102,86,221,154,225,108],\"firefox-container-15428@www.ugreen.com\":[1,99,41,54,5,10,68,216,36,113,174,176,146,59,233,29,42,25,104,132,114,224,57,125,167,209,242,246,59,209,136,42,217,97,211,222,114,57,196,170,151,60,121,152,238,130,178,55,189,192,202,87,128,10,40,151,214,4,15,164,163,46,227,157,90,226,92,40,152,92,122,112,218,57,69,127,16,55,179,144,157,249,107,129,156,87,29,246,146,73,39,67,35,75,75,61,239,69,196,57,71,99,172,81,184,25,88,87,81,182,110,195,166,210,74,177,98,74,52,82,159,68,164,76,243,206,152,149],\"firefox-container-15429@www.amazon.de\":[40,213,174,202,230,123,135,53,209,156,148,228,130,244,98,220,84,206,62,96,133,247,31,57,33,132,241,202,35,54,77,73,42,87,190,197,192,71,136,133,136,21,230,184,169,177,171,112,27,171,44,83,20,18,171,167,93,139,92,32,109,54,140,157,245,125,230,48,235,170,39,214,27,252,159,148,93,71,35,139,118,72,172,57,95,162,54,215,189,196,228,247,182,202,93,17,35,36,232,176,195,34,106,205,104,20,170,172,0,3,225,213,199,109,47,237,32,100,143,227,181,235,80,2,205,26,198,174],\"firefox-container-15432@disqus.com\":[54,34,9,82,148,220,127,140,1,42,175,49,201,66,28,130,6,31,202,154,202,59,125,185,44,1,46,168,196,104,25,171,17,87,41,182,64,136,58,58,191,90,44,35,219,150,198,178,77,78,250,105,173,114,97,157,199,76,194,177,20,37,106,64,123,122,74,106,26,217,35,65,132,28,42,95,125,177,55,193,64,21,211,53,165,0,188,68,166,214,249,2,68,177,129,139,202,236,12,154,163,231,11,85,246,169,151,121,2,58,82,184,127,58,76,108,66,115,30,200,29,216,154,110,80,188,119,251],\"firefox-container-15433@assassinscreed.fandom.com\":[18,150,151,19,205,198,171,199,77,62,165,246,190,112,158,215,127,50,191,210,85,213,237,18,227,231,62,175,65,49,170,121,183,201,158,135,171,195,208,22,197,156,163,184,92,166,244,47,124,174,16,103,24,17,224,212,247,45,177,255,199,104,205,42,106,155,228,135,152,6,87,21,207,42,212,241,144,53,69,218,125,225,112,231,178,239,0,49,71,226,47,252,216,214,240,90,3,178,70,63,138,217,31,162,34,182,117,53,182,202,130,44,225,226,95,77,154,52,0,238,212,184,151,213,174,51,78,182],\"firefox-container-15435@www.google.com\":[56,12,51,71,28,195,101,50,210,10,230,65,138,6,23,222,238,243,241,213,183,56,227,160,159,105,213,202,197,10,183,165,23,149,170,49,195,117,193,187,100,117,234,123,212,173,33,3,48,101,172,62,32,149,89,38,49,46,205,220,4,45,80,135,102,183,209,101,242,75,132,169,222,141,199,27,143,3,88,243,75,212,151,1,155,149,16,205,193,150,66,128,241,137,83,237,122,157,58,12,41,81,213,232,224,78,172,83,137,112,30,103,153,135,72,53,11,227,42,205,13,23,172,71,20,138,224,141],\"firefox-container-15435@ogs.google.com\":[251,33,134,47,66,56,222,108,178,171,208,20,175,75,241,88,162,231,105,51,109,72,115,20,146,68,103,173,193,24,15,255,178,87,164,132,178,214,229,115,18,25,136,94,31,163,3,116,140,226,184,114,83,207,139,95,145,135,41,10,167,31,213,74,30,35,32,155,67,58,172,148,213,66,1,136,115,237,23,251,143,251,188,161,18,244,53,0,175,14,35,240,58,38,36,104,166,238,249,4,113,39,155,228,162,68,97,88,146,220,184,68,192,200,47,239,240,176,69,49,2,230,208,148,210,205,74,143],\"firefox-container-15443@www.google.com\":[139,27,113,27,148,194,134,82,73,212,146,176,71,181,14,222,82,12,164,86,89,48,14,16,49,251,110,145,101,43,1,51,200,233,46,246,66,93,92,50,200,133,235,168,116,106,192,135,103,112,55,253,200,220,206,172,96,87,136,251,153,242,84,48,196,86,135,17,238,133,70,56,82,100,235,206,113,98,92,93,193,105,60,72,80,71,147,13,181,16,204,38,138,70,99,217,126,80,95,13,84,147,144,238,16,116,166,198,52,185,28,252,181,141,95,14,86,176,232,213,252,154,120,42,67,52,210,208],\"firefox-container-15443@ogs.google.com\":[154,190,240,117,33,141,94,46,147,171,128,124,146,0,152,70,76,107,152,212,73,64,13,119,22,154,31,34,98,79,20,153,113,244,207,4,53,142,163,30,177,182,35,107,81,123,56,157,255,59,56,240,228,124,254,30,35,1,4,30,46,102,131,118,245,190,70,27,189,0,63,177,215,178,83,102,81,96,90,187,115,174,123,123,103,87,94,211,246,64,2,26,60,0,223,228,254,205,119,172,227,230,226,38,77,243,201,188,133,113,55,4,61,84,245,139,210,127,236,209,111,71,160,232,146,48,215,180],\"firefox-container-4@www.paypalobjects.com\":[229,56,56,17,61,177,85,145,209,204,60,156,89,6,53,50,205,194,179,125,208,48,114,188,249,242,133,75,2,161,179,215,33,162,157,142,179,171,49,147,248,44,92,46,78,155,190,250,203,254,177,85,201,236,175,67,122,213,89,124,209,142,178,145,181,123,112,32,26,215,240,223,55,0,160,94,35,208,192,203,107,154,70,179,87,149,194,204,223,191,217,38,155,171,118,239,226,19,109,141,229,207,23,78,45,246,245,219,76,18,18,88,70,2,19,59,7,165,246,248,108,9,149,115,70,15,57,240],\"firefox-container-4@www.recaptcha.net\":[207,243,187,227,158,115,87,230,208,138,26,86,212,136,30,34,29,229,21,10,152,21,65,176,48,178,116,86,169,63,61,232,5,34,223,50,65,104,91,145,218,243,153,203,104,135,110,210,28,104,7,190,235,55,35,6,87,40,53,223,229,22,107,136,30,199,122,129,39,221,129,124,112,125,16,207,238,17,180,72,151,0,84,76,224,73,7,104,23,66,99,118,162,132,100,212,41,156,96,213,84,118,198,49,27,136,132,43,29,168,136,58,173,188,178,144,47,20,32,95,242,88,60,224,101,123,224,130],\"firefox-container-4@www.zimmerschluessel.de\":[65,14,139,76,72,96,184,125,84,8,71,132,237,4,212,86,235,142,127,13,172,240,137,83,200,39,116,36,107,189,182,185,60,224,213,85,240,168,117,116,12,253,123,158,237,239,163,244,19,159,215,67,250,241,58,214,45,208,87,53,7,173,64,65,182,137,100,194,101,209,81,91,47,175,49,254,95,196,202,219,56,246,51,124,1,118,155,36,108,254,61,62,121,209,174,11,15,111,48,173,7,96,166,73,117,116,49,209,83,49,14,169,21,143,96,158,249,26,121,58,248,206,112,154,32,15,248,191]}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1648033539759,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "0.1%",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "5",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}"
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment] 2022-03-24 22:35
My Fritzbox works fine. Both over fritz.box and the IP-address. Do you have any error messages related to CB in the browser console (Ctrl + Shift + J)?

**Comment by kkapsner** [comment] 2022-04-21 17:53
I still cannot reproduce your problem. Which version of Fritz!OS are you using?

Without you providing more information I unfortunately cannot help you.

**Comment by MysteryIII** [comment] 2022-04-24 11:21
I'm very sorry, I didn't respond earlier. This is the console output:
[![Bild canvasblockerfb0177j58.jpg auf abload.de](https://abload.de/thumb/canvasblockerfb0177j58.jpg)](https://abload.de/image.php?img=canvasblockerfb0177j58.jpg)

Also I just noticed that the upload interface of Abload.de (so only the inner "frame") won't load while Canvas Blocker is activated. I don't know if it's really related, as Canvas Blocker should work on this site at least, but it shouldn't interfere with local addresses.
I'm on FritzOS 7.29, but I think it already happened on previous version.

**Comment by kkapsner** [comment] 2022-04-24 16:00
It seems to be similar as #581. You seem to have something weird in the white/black/temporary white list...

ah... just saw the problem (did not notice at first because github formatted your settings):
```
"whiteList": "shoop.de,paypal.com,*.paypal.com,192.168.0.1,192.168.0.*",
```
The stars are an issue. CB does not use `*` for wildcards. If you whitelist paypal.com it automatically whitelists all subdomains. If you want to use whitecards you have to use RegExp. In the case of the local IPs it should be `^https?://192\.168\.0\.`.

But entering these invalid values should not break the page and this will be fixed.

**Closed** 2022-04-24 18:50 UTC
Labels: bug

**Comment by spodermenpls** [comment] 2022-04-24 20:43
@kkapsner The issue with wildcards within RegEx is a recurring problem, so I searched around a bit and found this RegEx generator site: https://regex-generator.olafneumann.org/ . What do you think of it? Maybe it could be referred to, to give RegEx-inexperienced users a little help at hand how to generate proper RegEx entries for site-specific values.

**Comment by spodermenpls** [comment] 2022-04-26 16:02
> I think the problem is not that they tried to create a RegExp. Often you can use `*` as a wildcard in domains. But CB does not support that. I created #613 to support that.

That's a good call. I wasn't implying though that people **were** trying to create RegEx'es, in opposite I meant they would've needed to do so, but weren't aware of that requirement, respectively usually not familiar how to lay out a proper RegEx, which made me think of linking such a RegEx generator.
