### ISSUE TITLE
Pages set to load on firefox startup will not load when Privacy Badger is installed

### ISSUE THREAD

**Issue by ewokuk** [kkapsner/CanvasBlocker#388] opened 2019-08-01 20:08 UTC
## Description
Any page I have set to open on startup in firefox (i.e. my homepage and any pinned tabs) will not load when canvasblocker is enabled. I get the throbber moving left and right at the top of the tab and it does this forever, with a blank page. As soon as I disable canvas blocker and restart firefox, problem vanishes and the pages load by themselves after a couple of seconds. Note this ONLY affects things set to automatically load on startup, even when they sit there not loading, i can still get them to load if i click on the relevant bookmark or type in the URL but they refuse to load by themselves on startup.

## Expected Behavior
Pages set to load on startup load as normal

## Current Behavior
As above.  Seems to be caused by also having Privacy Badger installed

## Steps to Reproduce (for bugs)
1. Have Privacy Badger and CanvasBlocker installed
2. Set a page to load as your home page on startup, or pin some tabs
3. Close and re-open firefox
4. Those pages will never load

## Your Environment

Latest CanvasBlocker
Latest Privacy Badger
Firefox x64 68.0.1
Win 10

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectDOMRect": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1564674898522,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "0",
	"historyLengthThreshold": 10000,
	"protectWindow": false,
	"protectDOMRect": false,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment] 2019-08-01 23:10
I found that I could not reproduce the issue when CB is simply disabled and reenabled. Does this help in your case as well?

**Comment by kkapsner** [comment] 2019-08-01 23:24
Also disabling the data URL protection seems to help.

**Comment by ewokuk** [comment] 2019-08-02 06:59
Yes after disabling CB and re-enabling CB the pages then load as soon as it is re-enabled

**Comment by kkapsner** [comment] 2019-08-02 08:13
For the current browser instance the disabling and re-enabling also works with Privacy Badger.
In my case this also helped after restarting FF. Is this also the case for you?

I'm not quite sure where to fix this issue. Maybe we should get some Privacy Badger people involved @ghostwords

**Comment by kkapsner** [comment] 2019-08-02 08:17
Can you also please try the latest alpha version (it's only for this issue...): https://canvasblocker.kkapsner.de/versions/

**Comment by ewokuk** [comment] 2019-08-02 08:24
Ok will have a look when I get home tonight

**Comment by ewokuk** [comment] 2019-08-02 17:59
Seems to be working ok with that alpha version

**Comment by kkapsner** [comment] 2019-08-02 22:01
Good - at least we know now what causes the issue...  still not sure how to fix it though.

**Comment by 9jkh** [comment] 2019-08-10 15:02
Just to add: CB has been causing severe hangs on one particular site. Disabling CB proved to be the fix. However, reading further into this here, where there seems to be a conflict of some kind between CB and Privacy Badger, whitelisting that site in PB, while keeping CB enabled, proved to be the better fix, since it allowed me to keep using CB.

**Comment by kkapsner** [comment] 2019-08-12 08:06
Good point with the whitelisting in PB.
As far as I see the problem is the order in which the extensions are loaded. PB intercepts a function that CB already altered and the settings for CB are not yet loaded so it force loads the settings which then fails (I'm not quite sure why that then causes the hangs).

But I'm still not sure if I can solve this problem in CB or the root problem lies in PB.

**Comment by 9jkh** [comment] 2019-08-12 14:14
No idea how or if this aligns with your observations noted above, but whitelisting that site in CB did nothing to stop the hangs. Only whitelisting in PB was effective — apparently — in resolving this issue.

**Comment by kkapsner** [comment] 2019-08-12 15:57
Whitelisting in CB works a little bit different and therefore does not help here.

**Comment by kkapsner** [comment] 2019-12-14 23:03
I am not able to reproduce the issue in FF 73, PB 2019.11.18 and CB 0.5.15RC2. Do you?

**Comment by 9jkh** [comment] 2019-12-15 14:01
Not at FF 73, running 68.3esr. Haven't noticed any issues since my post of 8/12/19.

**Comment by ewokuk** [comment] 2019-12-15 14:08
> I am not able to reproduce the issue in FF 73, PB 2019.11.18 and CB 0.5.15RC2. Do you?

I removed privacy Badger as it broke too many things so not sure if it still does it. Can probably be closed if it can't be reproduced in 73

**Comment by kkapsner** [comment] 2019-12-15 20:48
> Can probably be closed if it can't be reproduced in 73

Fine for me.

**Closed by kkapsner** 2019-12-15 20:48 UTC
