### ISSUE TITLE
Persistent high CPU load on some web sites

### ISSUE THREAD

**Issue by ms1121** [kkapsner/CanvasBlocker#253] opened 2018-09-11 20:20 UTC
While the tab is selected, I am seeing high CPU usage in Firefox on some web sites… as if a thread is remaining active and the process never completes.  When I disable CanvasBlocker in **about:addons** and select the tab again, Firefox CPU loading for the page has returned to its normal idle state.

Example: https://homebiogas.com/

**Comment by kkapsner** [comment] 2018-09-11 21:05
How many notifications do you see in the notification popup?
![grafik](https://user-images.githubusercontent.com/1105157/45387700-1fded380-b617-11e8-876a-0cb565aae2be.png)

**Comment by kkapsner** [comment] 2018-09-13 21:38
Can you please try the latest Alpha (you have to disable the normal first): https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha3

**Comment by kkapsner** [comment] 2018-09-16 10:45
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha4

**Comment by tavyra** [comment] 2018-09-27 23:13
I'm on 0.5.4 and the problem still exists. Here's an address that will produce the problem without fail: https://www.windowscentral.com/how-use-custom-environments-windows-mixed-reality

**Comment by kkapsner** [comment] 2018-09-29 21:14
Can you please check which protection causes the problems on the other pages?

**Comment by tavyra** [comment] 2018-10-05 20:34
I use ublock origin and umatrix, is there a rule or something I should add to keep this from happening? Disabling CB makes my cpu idle normally but I've only got like 70 notifications from ublock+umatrix+disconnect combined. I'm not sure what the other pages were that ended up freezing firefox and I can't think of any other add-ons that would be interfering.

Not knocking your efficiency either, with the exception of the random page that goes from 5% to 100% like a supercar, I haven't noticed any performance impact.

**Comment by kkapsner** [comment] 2018-10-06 10:07
I do not know of a specific rule. I also use NoScript which also helps.

With number of notifications I mean the number in the page action popup (see screenshot in first comment).

**Comment by kkapsner** [comment] 2018-10-23 21:38
Can you give an example link for amazon? It runs well for me.

The amiunique thing is known and there is not really anything I can do about it - they use a very poorly written script.
You can disable the audio cache temporarily to let it run a little bit faster. But I can tell you that it will say that you are unique...
If you want to test if the fingerprint is changing with every load you can use the CB test pages: https://canvasblocker.kkapsner.de/test/

**Comment by Leeweez** [comment] 2018-10-24 01:44
Here's a random link:
https://www.amazon.com/Ultraviolet-Sanitizer-Sanitizing-Portable-Bacteria/dp/B007DK8FKW/

Keep scrolling, and once you hit the reviews it turns into a slideshow. Turning off DOMRect immediately resolves the issue.

I disabled all other addons, and the issue is still exhibited.

**Comment by spodermenpls** [comment] 2018-10-24 02:18
@Leeweez I can't reproduce this issue either.. maybe open a new Issue, and share detail information about your configurations and console logs?

**Comment by kkapsner** [comment] 2018-10-24 18:39
Same for me. Page scrolls fine.

**Comment by kkapsner** [comment] 2018-10-31 20:57
What do you see in the page action popup: 
![grafik](https://user-images.githubusercontent.com/1105157/47818264-f8270480-dd57-11e8-9c2f-e90ec790120c.png)

**Comment by kokoko3k** [comment] 2018-11-05 12:01
Sorry for the delay, i see the following:
```Faked DOMRect readout on www.amazon.it (157)```

**Comment by kkapsner** [comment] 2018-11-09 13:06
Can you please give me your settings?

**Comment by kokoko3k** [comment] 2018-11-09 13:35
Here they are (i've whitelisted amazon)
```
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "www.amazon.it",
			"blockMode": "allowEverything"
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1541763252068,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "11",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.4
}
```

**Comment by kkapsner** [comment] 2018-11-10 11:55
Hm... I do not see anything bad there. Does the problem persist when you disable the DOMRect protection?

**Comment by kokoko3k** [comment] 2018-11-12 08:13
Hi,
if i disable  DOMRect API protection, the problem goes away.

**Comment by kkapsner** [comment] 2018-11-12 20:16
Hm... I still cannot reproduce but I recommend that you then only disable the DOMRect API for amazon and not whitelist it completely.

**Comment by kokoko3k** [comment] 2018-11-13 12:30
Thanks, but it is not clear to me how to disable just the DOMRect API for a specific site.
In the specific site option, i've "block only blacklist", but i'm unable to find where to set it, or maybe i'm completely wrong and there's another way (?)

**Comment by kkapsner** [comment] 2018-11-15 15:35
For all other searchers:
![image](https://user-images.githubusercontent.com/1105157/48563330-5d502d80-e8f4-11e8-8039-8f9d84934f79.png)

**Comment by Lucapz** [comment] 2018-12-05 06:06
Someone on a forum had an old Windows XP box that he had to disable CanvasBlocker on as it caused websites like Amazon to become choppy like others have mentioned and he all so had to disable it on a more modern Linux skylake box as 60fps media at Youtube would stutter but was perfectly fine when CanvasBlocker was disabled so something is causing a high overhead or I/O polling that it's not always practical to use?

It might be something to do with Firefoxes API as other extensions can become sluggish on certain pages as i've noticed this with lastpass taking forever.

**Comment by kkapsner** [comment] 2018-12-23 11:36
I always recommend to identify the part of CB that causes the slowdown (in the case of Youtube I would guess it's the DOMRect-API). The problematic parts can be disabled individually (also on a site by site level).

**Comment by kkapsner** [comment] 2018-12-30 11:58
It's working fine for me - what are your settings and versions (Firefox/CB)?

**Comment by codejodler** [comment] 2019-01-31 20:43
Hello Korbinian, 
I also noted excessive load after installing the CanvasBlocker addon/extension. Then i tried to figure things and found that another extension, EclipsedMoon (for the Palemoon browser) has a setting 'canvas.poison' checked, in the prefs section 'reduce fingerprinting',  and when i uncheck that, the abnormal load is gone, at least on the few sites i tried since then. 
This is not totally obvious since that Moon extension is supposed to fake useragents, but actually does a lot more.  
So my idea is that the two are somehow fighting over the final result :D  

I would not go so far as to notify the Eclipsed Moon developers. I mean, they're doing the best they can. 
I think CanvasBlocker should just include a comment directly in the prefs, that the user is responsible for having not any other plugin mingling into the Canvas business. 
Cheers,
mi

**Comment by kkapsner** [comment] 2019-02-02 11:12
Sounds like a good idea.

**Comment by mutantsushi** [comment] 2019-02-13 04:28
This is website that triggers persistent script/CPU warning:
https://paizo.com/community/forums/pathfinder/playtest

Also, it happens on Twitter.

The warning doesn't occur, but Disqus discussions won't even display without CB disabled.
(not even logged in to be able to comment, but Disqus comments won't even load with CB)

**Comment by kkapsner** [comment] 2019-02-13 13:26
I don't get a single CanvasBlocker notification or warning on this page. Please check the notifications to get to know which API/scripts trigger the CB protection.

Twitter is probably the DOM-Rect API. It usually gets a little bit better if you disable the notifications for DOM-Rect.

I have no clue about the Disqus problem (but I know that their technological approach is horrible). Can you give me an example page?

**Comment by AeliusSaionji** [comment] 2019-03-23 05:35
I've just installed this extension today and can attest to it causing serious performance issues.

Observe: https://aelius.keybase.pub/canvasblocker%20amazon%20image%20performance.mp4

**Comment by AeliusSaionji** [comment] 2019-03-23 05:38
Also, even when I'm not interacting with the Amazon webpage, firefox is chewing through 20% of my CPU when canvas blocker is loaded. Disabling canvasblocker and refreshing the page allows firefox to idle again.

**Comment by kkapsner** [comment] 2019-03-23 11:37
I am aware of this issue but have no good idea how to solve it. There is no good way to distinguish between fingerprinting and legit use of the DOMRect-API.

Maybe I should analyse the amazon code to get the exact problem...

**Comment by kkapsner** [comment] 2019-05-04 07:31
The code at amazon is not great. It seems to me that they read the DOMRect more often than necessary. The numbers I get when I count every readout are insane (several thousand for one mouse movement). So the only thing I can do is to improve the overall performance of the DOMRect API.

**Comment by kkapsner** [comment] 2019-05-04 11:45
I managed to get some performance improvements. The zoomed view at amazon is better but far of being good.

**Comment by kokoko3k** [comment] 2019-05-06 11:41
Thanks kkapsner!

I'm thinking...
Would it be possible to add an "antihammer" option so that CanvasBlocker wouldn't allow more than (insert number here) requests per second?

**Comment by manyplay** [comment] 2019-05-07 15:17
Hi,thx for the great addon!
Can you check the message system on ebay!
I have to disable the addon if i want to write a message...
The edit field is not writable...

**Comment by kkapsner** [comment] 2019-05-07 22:52
@kokoko3k I could implement that but it would not help the user of such sites as it would completely break them. And despite it being written poorly it's a legitimate use of the API.

@manyplay please open a separate issue for your problem with all the details needed.

**Comment by kkapsner** [comment] 2019-05-11 11:27
With the latest improvements the amazon page is usable. Not good, but usable.

**Comment by kkapsner** [comment] 2019-05-26 17:45
Please test the latest 0.5.9 as it has some performance improvements.

**Comment by kokoko3k** [comment] 2019-05-27 06:16
Definitely better, thank you!

**Comment by kkapsner** [comment] 2019-06-09 11:47
I think with 0.5.10 the performance is acceptable. So I will close this issue. If someone still has an example page that uses lots of CPU or is slow I can reopen this issue.

**Closed** 2019-06-12 14:01 UTC
Labels: bug

**Comment by vkvijay143** [comment] 2022-09-02 07:35
thank you so much..it's working for my website [https://ecogenn.com](url)

**Comment by buggsi** [comment] 2024-07-26 05:13
I was having performance issues on Amazon as well, when hovering on an image (it zooms in on it), if I move the mouse, the CPU would increase to 15% and memory would rise; at some point it reached 4GB for an Amazon tab, and the "zoom navigation" was choppy and slow. I use many extensions, and I pinpointed that CB was causing the problem. Enabling or disabling HW acceleration didn't help. So, after reading this thread, I found that indeed the DOM-Rect had the highest hits:

![image](https://github.com/user-attachments/assets/3068d3cf-fcc1-4c47-97be-446b87f6e48c)

I disabled it as you instructed here https://github.com/kkapsner/CanvasBlocker/issues/253#issuecomment-439082159 and now the image zooming is fluid again. My question is, when disabling the DOM-Rect API for a specific site, does it affect the fingerprinting blocking?

**Comment by kkapsner** [comment] 2024-12-22 02:22
> I used **amazon.***, is that a correct usage?

It will match the mentioned domains. But also something like `amazon.evil.attacker.net`.

> My question is, when disabling the DOM-Rect API for a specific site, does it affect the fingerprint faking?

It affects the fingerprinting through the DOM-Rect API. But all the other ways are still protected.
