### ISSUE TITLE
Hanging script reported  on browser startup

### ISSUE THREAD

**Issue by Alexander--** [kkapsner/CanvasBlocker#17] opened 2015-01-30 22:48 UTC
The extension slows browser to crawl during startup. "Script not responding" alert mentions

```
resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/uniqa/.mozilla/firefox/vhlwek37.default/extensions/CanvasBlocker@kkapsner.de.xpi!/bootstrap.js ->
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:335x
```

Same thing happens, when any Jetpack addon is (re)started. I believe, that one of causes lies in the fact, that CanvasBlocker ignores current state of tabs (it switches to tabs even when they are in background or unloaded). I am using "fake readout api" btw.

**Comment by kkapsner** [comment] 2015-01-30 23:04
Which Firefox version are you using?
Which OS?
Which URL is open in the tab that causes the problem?

The startup on my machine is OK...

I do not know what you exactly mean with "it switches to tabs". CanvasBlocker should not do any tab switching at all.
Can you give me a minimal way to reproduce the problem?

**Comment by Alexander--** [comment] 2015-01-30 23:10
> Can you give me a minimal way to reproduce the problem?

open several hundreds (merely!!) tabs in >2 tab groups. Exit firefox. Re-enter Firefox with tab restoration enabled. For bonus fun install some other Jetpack extension (choose any for added fairness).

I am using Firefox 35.

**Comment by Alexander--** [comment] 2015-01-30 23:37
Actually disregard that, the issue seems to be reproducible with many Jetpack addons on this version. The browser does not whine about native addons, but attempts to push the blame for slow startup on Jetpack addons in order of launch. Still, some addons hang less, compared to others (probably due to lack of per-window hooks). Woud it, perhaps be possible to postpone that stuff until tabs are loaded? Is there even a way to do that?

**Comment by kkapsner** [comment] 2015-01-31 10:39
I run a quick test with four tab groups and 200 tabs each and got no problems...
 OK "no problems" is not quite true: it took around one minute to start firefox but 800 tabs are quite a lot. But no hanging script.

And it would defeat the whole point of canvasblocker if I would postpone the stuff until the pages are loaded. The fingerprinting is usually done at the moment the script is loaded which can be much earlier.

**Comment by kkapsner** [comment] 2015-03-26 18:29
Since I can not reproduce the problem and got no further information I will close this issue.

**Closed by kkapsner** 2015-03-26 18:29 UTC
