### ISSUE TITLE
Hangs with 100% CPU load on certain sites

### ISSUE THREAD

**Issue by haarp** [kkapsner/CanvasBlocker#119] opened 2017-06-14 16:07 UTC
Canvasblocker appears to cause an infinite loop somewhere on certain sites, that cannot easily be recovered from. One has to kill the content process for it to react again.

This is in fake readout mode.

Specifically, this happens on the Mister Spex shop, when a product page is opened. Example: https://www.misterspex.de/brillen/co-optical-morrison-blk_f6527289.html. It seems related to the "Virtual Mirror/Fitting" function.

Calling file: 
	https://www.misterspex.de/INTERSHOP/static/WFS/MisterSpex-MisterSpexDE-Site/-/-/de_DE/js/twoD/2d.fitting.min.js?bust=17.24.1.2.132.1497261313 line 1 column 1355031
	https://www.misterspex.de/INTERSHOP/static/WFS/MisterSpex-MisterSpexDE-Site/-/-/de_DE/js/twoD/2d.fitting.min.js?bust=17.24.1.2.132.1497261313 line 1 column 1354841

**Comment by gtackett** [comment] 2017-06-19 03:36
I think this may be happening with www.hexwar.com as well.

**Comment by kkapsner** [comment] 2017-06-19 06:21
It is a known and unsolvable issue that the faking of the readout can cause hanging of the site. Usualy that's due to big canvas that get read. There are two ways to deal with that: first you can, obviously, add this pages or the specific script to the whitelist or second you can play with the maximum faking size. I think the later is save as long you do not set the size below 100000.

**Comment by gtackett** [comment] 2017-06-19 14:46
Thanks!! 
Galen

**Comment by haarp** [comment] 2017-06-19 15:47
Indeed, increasing the max size helps. In my case, 100k wasn't enough, but 1000000 (1M) works. Thanks for the tip. Would it make sense to make this a default?

**Comment by gtackett** [comment] 2017-06-19 17:41
Haven't tried it out myself yet so there's not much I can say.
 If you're planning on any other updates, perhaps you could roll this, with the other updates, into a "beta" release? (I don't know how hard that may be...)

Galen

**Comment by RoxKilly** [comment] 2017-06-26 21:57
@haarp wrote:
> Indeed, increasing the max size helps. In my case, 100k wasn't enough, but 1000000 (1M) works. Thanks for the tip. Would it make sense to make this a default?

What's the unit of this size measure?  100k what?

**Comment by spodermenpls** [comment] 2017-06-27 14:50
> What's the unit of this size measure? 100k what?

Pixels.

**Comment by kkapsner** [comment] 2017-06-27 15:49
@gtackett: I'm not sure what I should roll out. The change of the default value of that setting?

**Comment by gtackett** [comment] 2017-06-27 23:22
Yes, that's what I meant.

**Comment by kkapsner** [comment] 2017-06-28 20:56
Changing the default value is quite easy, but since this lowers the security I prefer to have the user change that by purpose.

**Comment by spodermenpls** [comment] 2017-06-28 22:07
I would suggest that you put at least a recommendation in the description text (like not to go below 10.000 pixels, and to set the max depending on the power of your device). The maxSize-function is critical to avoid annoying browser freezes caused by big, yet harmless images, so it would be helpful for new users to give them at least a little guideline (especially when it comes to a more "mainstream" audience, who could be easily turned off by CB without a pixel limit, being confronted with occasional freezes).

**Comment by RoxKilly** [comment] 2017-06-28 23:14
> I would suggest that you put at least a recommendation in the description text (like not to go below 10.000 pixels, and to set the max depending on the power of your device).

I'm confused. If this is a max setting, wouldn't a low max be easier on the CPU by limiting the extension to small canvases? So why are we saying "don't go below 10,000" as though lower would be more CPU-intensive?  Shouldn't we be saying "don't go above 1M" (or whatever number)?

**Comment by spodermenpls** [comment] 2017-06-29 05:09
If the maximum size is set too low, bigger fingerprinting canvas' are gonna be white-listed from CBs protection, undermining the whole purpose of this extension.
Unfortunately, there is no survey data on how big an average canvas is.. Websites might want to use canvas' that aren't bigger than necessary, to avoid unnecessary traffic and data to process. Browserleaks for example uses a canvas with 6.600 pixels, so a 10.000 limit (for slow devices, like my phone) would make sense in my mind, to be put as a guideline in the description text.

**Comment by kkapsner** [comment] 2017-06-29 05:18
@spodermenpls: great suggestion. I will adjust the description accordingly.

@RoxKilly: Yes, it's a max setting. Everything that is bigger than the max fill not be faked. So big canvases which create a lot of CPU usage when faked will not be touched and therefore freezes are less likely to happen. But if you go below a certain size some fingerprinting canvases will also not be touched.

@all: but it seems that the webExtension version of this addon is much faster (do not ask me why - I did not change much of the actual computing) - or maybe the nightly version of Firefox is faster. In the example of this issue I do not see a freeze with them.

**Comment by gtackett** [comment] 2017-07-06 12:40
> it seems that the webExtension version of this addon is much faster That's good news, especially since Mozilla is driving everyone in the webext direction pretty forcefully. Not every extension developer has been pleased, as I'm sure you're more aware than I am.

Galen

**Comment by kkapsner** [comment] 2017-07-06 15:43
I was not pleased either...

**Comment by kkapsner** [comment] 2017-07-29 11:50
Since the setting solves the problem and the new WebExtension does not show the problem entirely I will close this issue. You can reopen it if you feel the need for it.

**Closed by kkapsner** 2017-07-29 11:50 UTC

**Comment by kkapsner** [comment] 2017-09-23 21:23
No wonder this page hangs a little bit... it reads a canvas 227 times.

**Comment by kkapsner** [comment] 2017-09-28 21:36
Its 227 times the same canvas with exactly the same content...
