### ISSUE TITLE
Disable on a page doesn't effect the website

### ISSUE THREAD

**Issue by andreapx** [kkapsner/CanvasBlocker#707] opened 2024-04-19 08:24 UTC
## Description
I have a problem with Grafana (hosted in LAN): until yesterday the Grafana webpage was working without a problem, now it trows an error.
If I completely disable CanvasBlocker addon, Grafana starts to work, but it I enable CanvasBlocker and disable it in the Grafana website, the page won't load.

## Expected Behaviour
A complete shut off if I disable it in a single website

## Current Behaviour
CanvasBlocker still does something when disabled on a single website

## Steps to Reproduce (for bugs)

1. create a fresh Firefox profile
2. Install CanvasBLocker
3. open Grafana webpage (hosted in LAN)
4. see the meggase:  "If you're seeing this Grafana has failed to load its application files "

## Your Environment

* CanvasBlocker Version used: 1.10.1
* Firefox version incl. 32- or 64-bit: 125.0.1 (64 bit)
* Operating System and version (desktop or mobile): Windows 10
* Installed addons: in the new profile no other extensions are present

## Your Settings
~~~ json
 {
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "172.20.0.14",
			"blockMode": "allowEverything",
			"blockDataURLs": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1713514203754,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "22",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by spodermenpls** [comment] 2024-04-19 11:29
@andreapx This is a known regression (https://github.com/kkapsner/CanvasBlocker/issues/705) of the latest CanvasBlocker update, it will be fixed in the next version. In the meantime you can switch to the latest beta version (self-hosted on https://canvasblocker.kkapsner.de/versions/?C=M;O=D), where the fix(es) are already included, just make sure to disable the "regular" CanvasBlocker when the beta version is enabled.

**Comment by spodermenpls** [comment] 2024-04-19 14:35
@andreapx That depends mostly on the speed of the manual code review done by Mozilla, since CanvasBlocker is one of its "recommended addons" and has to jump through that hoop, before it is publicly available. But as I've said, the beta version including the fix is already there, it just needs a few clicks to install it.

**Comment by kot0dama** [comment] 2024-04-21 13:53
Thanks for the bug report, I was about to file a similar one while investigating my own Grafana issues :)
And also, thanks for the great extension, keep up the good work !

**Comment by andreapx** [comment] 2024-04-24 07:32
@spodermenpls I've installed the latest beta (1.10.1), but the problem persist, I've disabled Canvas blocker in a single website (Grafana), but I still have the problem. If I completely disable it, Grafana works.

**Comment by spodermenpls** [comment] 2024-04-24 08:02
@andreapx The latest beta is named 1.11 (https://canvasblocker.kkapsner.de/versions/?C=M;O=D), 1.10.1 is the old and faulty release version. Over at #705, two people reported that the changes in the beta version fixed the Grafana issue, so I'd be surprised if it really doesn't work in your case.

**Comment by andreapx** [comment] 2024-04-29 15:24
> @andreapx The latest beta is named 1.11 (https://canvasblocker.kkapsner.de/versions/?C=M;O=D), 1.10.1 is the old and faulty release version. Over at #705, two people reported that the changes in the beta version fixed the Grafana issue, so I'd be surprised if it really doesn't work in your case.

@spodermenpls I'm on V 1.11.20240417 but I still have the problem... :(

**Comment by spodermenpls** [comment] 2024-04-29 16:17
@andreapx That's unfortunate, I guess there's still some work to do for @kkapsner .

**Comment by heyarne** [comment] 2024-05-04 20:06
Not sure if this helps, but I lost the whitelist when installing the beta. During the setup screen I applied the convenience settings and the reCAPTCHA fix, and Grafana is working fine again for me.

**Comment by spodermenpls** [comment] 2024-05-05 07:53
@heyarne What do you mean by "losing the whitelist", I guess the fact that the Beta version is installed from scratch, and doesn't contain/import any of the settings made by a user inside the normal release version?

@andreapx Does Grafana work with the Beta version, when you use the same settings as you have with the release version, in particular withe the custom reCAPTCHA setting? You can use the "save" and "load" feature in the settings panel, to export and import the settings between "release" CB and "beta" CB very quickly.

**Comment by smurfix** [comment] 2024-08-15 08:04
The current beta fixes my Grafana problem. *Whew*.

Any idea what the hold-up is? 3+ months for a regression fix is kindof uncomfortably long.

**Comment by kkapsner** [comment] 2024-12-22 03:04
Close as a duplicate from https://github.com/kkapsner/CanvasBlocker/issues/705

**Closed by kkapsner** 2024-12-22 03:04 UTC
Labels: duplicate
