### ISSUE TITLE
Fake readout API breaks account.progressive.com without notice

### ISSUE THREAD

**Issue by RoxKilly** [kkapsner/CanvasBlocker#122] opened 2017-08-13 17:21 UTC
To replicate,

1. Enable fake readout API
2. Go to https://account.progressive.com 
3. Use fake credentials to login

**Expected outcome**: An error message telling you that the login is invalid, and CanvasBlocker should inform the user that it modified the page

![10](https://user-images.githubusercontent.com/12346501/29251796-c75fae06-8029-11e7-86bb-f783fa2a41f7.png)

**Actual outcome**: The page just reloads with a blank form as if nothing happened. There is no notification from CanvasBlocker making it difficult for the user to understand why the page is not working.

To get the page to work, I've had to either disable CanvasBlocker or add `account.progressive.com` to the whitelist.

**Comment by kkapsner** [comment] 2017-08-13 20:09
This has the same root cause than #121. It will be fixed in the next version.

**Closed by kkapsner** 2017-08-13 20:09 UTC
Labels: duplicate
