### ISSUE TITLE
"CanvasBlocker is slowing down firefox, terminate?" Canvasblocker hangs firefox until the process is terminated on specific website.

### ISSUE THREAD

**Issue by bucketcat** [kkapsner/CanvasBlocker#648] opened 2023-04-02 23:42 UTC
## Description
"CanvasBlocker is slowing down firefox, terminate?" Canvasblocker hangs firefox until the process is terminated on specific website.

This site specifically, navigate to any article. . https://helpdeskgeek.com/ Never seen this before, except when being memory capped which I wasn't in this case.

Firefox version 111.0.1.

## Expected Behavior
The browser doesn't hang.

## Current Behavior
The browser hangs until canvasblocker process is terminated.

## Possible Solution
Kill canvasblocker process.

## Steps to Reproduce (for bugs)

1. Navigate to one of the god awful, useless piece of junk SEO garbagemill articles hosted at "https://helpdeskgeek.com/". I clicked on a hyperlink from superuser, hat of course had nothing to do with the question asked. Nevertheless, that's step one.
2. Realize that the site is an NLP-generated SEO-optmized spam blog. Try to leave, I used the Alt+Left Arrow macro on firefox, I.e. return.
3.???
4. Profit... I mean, the browser hangs completely, after a while firefox displays a pop-up with the option to terminate CanvasBlocker. That resolves the issue, allowing me/you to get out of that website and add it to your pyhole never to be seen again.

## Context

I would like to have my browser not crash.

No.

I can't exactly give all my setting, other plugins and all the junk I run that break stuff left and right... But, tracking protection, max safety, webgl off etc. As close as you can come to Tor browser besides auto-clearing of cookies and cache. Other plugins active at the time = Ublock Origin with a plethora of custom filter lists and network lists. Rest of the plugins would not play a role.

## Your Environment

* CanvasBlocker Version used:
Latest version through firefox, unless there was an update in the last 4 hours.
* Firefox version incl. 32- or 64-bit:
111.0.1, 64Bit
* Operating System and version (desktop or mobile):
W10 enterprise
* Installed addons:
Ublock Origin with lots of custom filters.
Domains blocked=
1. Google analytics/SEO crawler,
2. Google syndication
3.  cdn.snigelweb.com
4. quantserve.com
5. btloader.com

## Your Settings

**I converted the json to txt, since github does not support json files here for some reason.**
~~~ json
<!--- Copy your CanvasBlocker settings here. -->
<!-- They can be retrieved by checking the expert mode and going to export settings. -->
<!--- You may consider deleting personal data - especially the "persistentRndStorage". -->
~~~

[CanvasBlocker-settings_2023-04-02_23-37-09.txt](https://github.com/kkapsner/CanvasBlocker/files/11133629/CanvasBlocker-settings_2023-04-02_23-37-09.txt)

**Comment by bucketcat** [comment] 2023-04-02 23:50
Note, I wont be available for any follow up. Hopefully a simple bug report is somewhat useful in finding the root cause.

**Comment by kkapsner** [comment] 2023-04-07 18:47
Since I cannot reproduce your problem (Firefox froze temporarily after adding ublock on that site but complained about the site and not the CB) and you are not available for any follow up I do not know how to proceed with this but closing it...

One suggestion from me would be to disable notifications on DOMRect events. If the problem still exists with this disabled you can post it here and I can reopen the issue.

**Closed by kkapsner** 2023-04-07 18:47 UTC
