### ISSUE TITLE
Firefox crashing  (cyberfox)

### ISSUE THREAD

**Issue by jugi1** [kkapsner/CanvasBlocker#90] opened 2016-11-18 15:06 UTC
Canvas blocker is crashing Cyberfox browser after updating to latest version 0.3.3.
Please fix this.

Usually it shows xul.dll error or similar, and browser must be restarted.

**Comment by kkapsner** [comment] 2016-11-18 15:35
Which version were you using before?
Which version of Cyberfox are you using?
Can you give a screenshot of the detailed error message?
Which XPI are you using? That from AMO or the unsigned from github?

**Comment by jugi1** [comment] 2016-11-18 18:31
I was using canvas blocker 0.3.2 (was working fine) from official 
https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/
Browser Cyberfox was crashing in last version (50) and version before that also.

I had to switch off extensions, one by one, to find crashing issue.
I even did clean browser reinstall.

Now I am trying to reproduce crash, take screenshot, and copy error message...

**Comment by jugi1** [comment] 2016-11-18 19:21
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Cyberfox.exe
  Application Version:	50.0.0.6163
  Application Timestamp:	582aab58
  Fault Module Name:	xul.dll
  Fault Module Version:	50.0.0.6163
  Fault Module Timestamp:	582aac56
  Exception Code:	c0000005
  Exception Offset:	00a51855
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	10266
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262



![error](https://cloud.githubusercontent.com/assets/23556919/20443285/88e09d32-adcc-11e6-87a3-9b41f493fc43.jpg)

**Comment by kkapsner** [comment] 2016-11-19 08:34
I'm not able to reproduce your problem.

Are you using the x86 or x64 version of Cyberfox?
Which OS are you using?

**Comment by jugi1** [comment] 2016-11-19 10:08
x86
Windows 8.1

PS
I switched to other canvas defender extension,
until this issue is resolved.

**Comment by kkapsner** [comment] 2016-11-19 13:38
I'm still not able to reproduce the problem on Windows 7 or 10 (I have no 8.1 machine).

Does the error also occur in the x64 version of Cyberfox?
When does the crash happen? On browser startup? When you visit a specific site?

**Comment by jugi1** [comment] 2016-11-19 17:26
Crashes where in Cyberfox x86 ,( portable also),
I am not using x64 anymore.

Crashes don't have any specific time, or site,
but they occur during browsing time (not on startup).

(Maybe it is when combined with NoScript or  other extension,
but it never happened like this before )

**Comment by kkapsner** [comment] 2016-11-24 23:33
Hm... I'm sorry but this is too vage for be to do anything - there's just no point where I should start. My bet would be that it's a bug in Cyberfox that just happens to be triggered by CB.

But there will be a new version soon that improves the performance - maybe that also helps in your case.

**Comment by kkapsner** [comment] 2016-11-26 16:50
Version 0.3.4 is out - it should be avaiblabe for update soon. Please check if your problem is solved.

**Comment by jugi1** [comment] 2016-11-28 21:22
Thanks.
I will report after few days of testing.

**Comment by jetwhiz** [comment] 2016-11-28 21:42
I'm also experiencing something similar to this, but I don't think it will be easy to track down the problem since it happens very randomly.  Sometimes just reading text in a browser it will freeze up and crash the browser.  

I am also using NoScript and uBlock Origin, so it might be a combination of these causing the issue.  

@jugi1 -- do you have Electrolysis enabled?

**Comment by jugi1** [comment] 2016-11-29 12:19
Electrolysis is disabled.

browser.tabs.remote.autostart  (false)

Note:
I disabled NoScript and browser still crashed sometimes

**Comment by kkapsner** [comment] 2016-12-17 09:30
New version - new luck. Please test with the latest version when it's reviewed by Mozilla.

**Comment by jugi1** [comment] 2016-12-17 12:59
Thanks.

I am using 0.3.4 for few days, after other extensions and browser updates,
and no crashes so far also.

**Comment by kkapsner** [comment] 2016-12-17 14:11
0.3.5 should be available soon (pending for review).

**Comment by jugi1** [comment] 2016-12-19 12:36
0.3.5 is good so far.
No crashes.
Thanks !

**Comment by kkapsner** [comment] 2016-12-23 12:39
Great - I will then close this issue. If you see crashes again, you can reopen it.

**Closed by kkapsner** 2016-12-23 12:39 UTC
