### ISSUE TITLE
New version totally killed ffox 61 android

### ISSUE THREAD

**Issue by crgithubmoth** [kkapsner/CanvasBlocker#215] opened 2018-07-21 18:31 UTC
## Description
I have many open tabs, hundreds,  but never more than a dozen loaded at a time.
I use a a Samsung Tab A tablet with 2gb ram, Android 7.
Since canvasblocker  updated  , firefox is kaput.
Every time I start firefox, it tries to load the last tab I had open.
It never loads, but I get the stop stuck script dialog. 
Whether I stop it or not, ffox switches to another random not-loaded tab,
With the stop script dialog saying canvasblocker.
This repeats until everything on my tablet has terminated.

I tried to open the addons tab, but it never loads.
I tried closing other tabs, but after crash + restart they are all back.
I have cleared cache, restarted tablet, gone offline, tried this all many times,
Just can't get any tabs to load before it crashes.

(Waterfox for android started just fine, but I got the update page for canvasblocker,
So I went  to addons and disabled it  -- not taking a chance until firefox is recovered.
)
## Expected Behavior
Canvasblocker should never be loading an unloaded tab!
## Current Behavior
Canvasblocker keeps loading tabs until ffox uses all ram and everything running terminates.
## Possible Solution
Never load a tab I did not select
## Steps to Reproduce (for bugs)
Maybe:
1. On a 2g ram system, Open tabs until ffox slows
2. Shut down ffox, restart , open some more tabs. Do this 3 times
3. Install canvasblocker
4.restart ffox

## Context

Firefox never does anything but crash

AFAICT Android does not give me access to create a new profile without rooting my device.

## Your Environment

Samsung Tab A , 8 cores, 2gb ram
* CanvasBlocker Version used: latest
* Firefox version incl. 32- or 64-bit:
61 android
* Operating System and version (desktop or mobile):
Android 7
* Installed addons:
   Ublock origin
   Umatrix
Several more, can't open addons tab to get a list

## Your Settings

Unable to comply. IIRC set to no readout?

Delete the "persistentRndStorage"? How?

**Comment by kkapsner** [comment] 2018-07-21 18:37
This is bad... and I'm sorry for this problem.
I do not know how this can happen - there is nothing I do to not loaded tabs.

What is the exact message in the "stop stuck script dialog"? The script with the problem should be mentioned.

**Comment by kkapsner** [comment] 2018-07-21 18:39
On Desktop-Firefox only the last open tab is loaded.

**Comment by kkapsner** [comment] 2018-07-22 09:18
I need some help with this problem as I do not have an Android device available to test and/or reproduce the issue.

**Comment by kkapsner** [comment] 2018-07-24 13:10
Please answer my questions. Otherwise I'm not able to help you.

**Comment by crgithubmoth** [comment] 2018-07-27 17:35
I have tried firefox beta 62, so far it is ok.
I don't have a list of extensions I was using,
And my tablet is not rooted so I do not know how to get a list.
I installed the ones I recalled, still ok.
I will let you know if I see any change
Did you get my screenshot of the error message?

**Comment by kkapsner** [comment] 2018-07-27 20:50
No - I did not get any screenshot.

Maybe there is a way to get the addon list out of a backup.

**Comment by NewGen66** [comment] 2018-07-28 01:09
@kkapsner 
Issue: latest version is conflicting with Random Agent Spoofer (Inject script turned on to spoof screen resolution)
Latest version of CB and RAS fights with each other and CB does not load on time and makes most off tests red-failed
http://kkapsner.github.io/CanvasBlocker/test/detectionTest.html

While Version 0.4.6alpha20180702 works fine with RAS
 I use firefox 54

Solution:
1. I can send you donation to work on upgrade RAS (for me only)as it is not updated from 2 years from dbryne
2. Make changes to latest version so that it does not conflict with script injection for screen  resolution spoofing. (0.4.6alpha20180702 works fine)
3. IF we can chat fast using sk y p e or any other program please let me know

Thank you so much

**Comment by kkapsner** [comment] 2018-07-28 11:43
One test even fails when using RAS alone...

But I found the problematic code and it will be fixed in the next version.

PS: Why are you using FF 54? I would use ESR or the latest version to get security patches.

**Comment by NewGen66** [comment] 2018-07-28 14:02
Hey KKapsner , Happy to hear you.
Thank you so much.

I will test Firefox ESR now.
Also i am using firefox54 because RAS will not work later versions.  and i am not able to change useragent, screen spoofing in latest version of firefox.


Could you add screen size spoofing option if its doable.

Thanks for you work.

**Comment by kkapsner** [comment] 2018-07-28 22:11
Please open a new issue with your feature request. There we can discuss in detail how this should be done.

**Comment by kkapsner** [comment] 2018-07-31 13:59
Version 0.5.2 is out which solves the RAS issue.

**Comment by NewGen66** [comment] 2018-07-31 16:28
Thank you so much

**Comment by NewGen66** [comment] 2018-07-31 16:40
I noticed that RAS script injection induce a failure of *property descriptor* when using CB in *fake at input*

property descriptor: test failed


When script injection at RAS is turned off then all tests run 
![capture](https://user-images.githubusercontent.com/41809366/43473709-873cdfe0-94b6-11e8-844b-1fc023dacafb.JPG)
fine

**Comment by kkapsner** [comment] 2018-07-31 18:42
If you use RAS completely alone it makes this test fail. That's because they inject old CB code.

**Comment by NewGen66** [comment] 2018-07-31 18:57
Wow you are right.
This is problem of RAS and not of CB.
I will disable *Screen size spoofing and change resolution manually.

is it possible to add screen size spoofing option in CB?

**Comment by kkapsner** [comment] 2018-07-31 19:01
I think it's possible. But as mentioned above: please open a new issue with that feature request.

**Comment by rugk** [comment] 2018-07-31 21:44
As such, this issue here is solved, is not it? SO you can close this one?

**Comment by crgithubmoth** [comment] 2018-08-01 12:00
The unresponsive script was require.js:11

**Comment by crgithubmoth** [comment] 2018-08-01 12:13
Retest on ffox 61: 
Now  unresponsive script was  lists.js:22
I suspect ffox 61 is crashing before it auto updates to new canvasblocker.
I did get an auto update on waterfox, it is working fine.

**Comment by crgithubmoth** [comment] 2018-08-01 12:24
Correction: waterfox loads separate cb settings page fine, but
In addon page, clicking on cb loads a 10% height frame with the settings page in it.
Waterfox would not artach the screenshot here.

**Comment by crgithubmoth** [comment] 2018-08-01 12:31
Screen size spoof would be great!

**Comment by NewGen66** [comment] 2018-08-01 13:08
@crgithubmoth 
I opened a feature request here for same

https://github.com/kkapsner/CanvasBlocker/issues/220

**Comment by kkapsner** [comment] 2018-08-01 22:15
Have you tried to start Firefox in safe-mode? https://support.mozilla.org/en-US/questions/500031 (I know it's old...)

**Comment by crgithubmoth** [comment] 2018-08-09 13:01
I did not see how to do android safe mode. Did I miss it?

**Comment by crgithubmoth** [comment] 2018-08-09 13:07
Ok, firefox focus won't display the answer. Waterfox works.
Time to get x terminal installed...

**Comment by NewGen66** [comment] 2018-08-10 16:25
While using CB with firefox 54 and all tests are green. this thing is killing my gmail account

 **This account is currently being used in one other location.
(Location may refer to a different session on the same computer**.

**Comment by Thorin-Oakenpants** [comment] 2018-08-12 17:42
Hey, NewGen66
- Firefox 54 was obsolete when 55 was [released](https://wiki.mozilla.org/Release_Management/Calendar) 2017-08-08 - that's **over a year ago** !
- Firefox ESR 52.x is still supported (security patches only), and although it has *some* web ext in it, it really requires legacy extensions. Don't mix web ext with old browsers (you didn't say what version of CB you are using)
- But it's all a bit of a moot point, because ESR52.x branch will also be no longer supported come 5th Sept (see release link above).

I don't think it's worthwhile for kkapsner (or anyone for that matter) to deal with unsupported legacy issues (and RAS is a legacy extension as well - AFAIK it's not even maintained any more) on a year old browser

**Comment by NewGen66** [comment] 2018-08-14 12:33
@Thorin-Oakenpants 


I will shift to something different than this combination .

RAS is the addon making problems.

Thanks for your time @Thorin-Oakenpants

**Comment by kkapsner** [comment] 2018-08-31 18:02
What's the state of the actual issue? Is this solved?

**Comment by kkapsner** [comment] 2018-09-13 22:29
I assume this issue is solved. If you still have problems you can ask me to reopen it.

**Comment by crgithubmoth** [comment] 2018-10-18 21:48
This problem did eventually recur with v0.5.4,
But I was able to deactivate it.
I have not seen any problem with 0.5.5.
Thanks for the fix!

**Comment by crgithubmoth** [comment] 2018-10-18 22:03
I spoke too soon:
Waterfox 60.1 w. V0.5.5 is getting stuck script repeatedly on panopticlick.eff.org results page,
But not by simply loading the page.
Not sure how to reproduce, but it is not a 1-off.

I will try restarts, etc.

**Comment by crgithubmoth** [comment] 2018-10-19 16:42
1. Exit waterfox while panopticlick results are showing  
2. Close browser
3. Restart browser 
4. Reload previous session
Result:
Continuous popups: stuck scripts
Checking block this script does not stop the same script from running for
Some of the CB scripts.

**Comment by kkapsner** [comment] 2018-10-19 17:34
Waterfox 60.1? Where did you get that?
I can only find 56.2.3. And with that (but on desktop) I'm not able to reproduce your problem... is it always the same CB scripts that are stuck?

**Comment by crgithubmoth** [comment] 2018-10-20 16:40
It is on google play store.
I think it is an android-specific release.
There is a link to it on waterfox website.
The scripts vary, but only from CB

**Comment by crgithubmoth** [comment] 2018-10-20 17:28
WF 60.1 : 
CB 0.5.5 is acting very different
Lists  option is missing 
Workaround: use block everything mode
I could not recreate the panopticlick issue on my old WF 56.1beta copy

**Comment by kkapsner** [comment] 2018-10-21 11:49
Do you have the expert mode active? The lists only appear when it's active.
Or did you hide them? Please post your settings.

PS: Actually I recommend using url specific values instead of the lists, if possible.

**Comment by kkapsner** [comment] 2019-01-31 23:31
Issue still present? Even with all the latest versions?

**Comment by kkapsner** [comment] 2019-02-27 23:22
I will close this as I got no reply. If you still have this problem I can reopen this issue.

**Closed by kkapsner** 2019-02-27 23:22 UTC
