### ISSUE TITLE
FF 56.0.2, macOS 10.10.5: 100% CPU, not responding when trying to quit FF

### ISSUE THREAD

**Issue by GuitarTab** [kkapsner/CanvasBlocker#168] opened 2017-12-17 20:27 UTC
(I'm a COMPLETE NOOB, so sorry, no geek jargon here ;)

After I updated CanvasBlocker today, the Activity Monitor shows 100+ % CPU for FF.

When trying to quit, FF is not responding.

Issues completely disappear when CanvasBlocker is disabled.

**Comment by kkapsner** [comment] 2017-12-17 20:35
To which version were you updating? 0.4.3a, b or c? Can you please try one of the betas: https://github.com/kkapsner/CanvasBlocker/releases/
Does the problem also occur when you use a fresh Firefox profile?
Which other addons did you have installed?

PS: You don't need geek jargon here ;)

**Comment by kkapsner** [comment] 2017-12-17 23:12
Can you please also try with Firefox 52 and/or Firefox 57?

PS: for security reasons you should not use Firefox 56 as it does not get updates any more. Use Firefox ESR (52) or Firefox 57.

**Comment by nerbrume** [comment] 2017-12-18 13:42
I can confirm the same behaviour on Ubuntu 17.10, which is still using Fx 56.
Even when staying idle, Firefox is eating 100% of a core. This does not trigger at start, but later, and prevent the closing of Firefox.

**Comment by GuitarTab** [comment] 2017-12-18 15:06
> To which version were you updating? 0.4.3a, b or c?

0.4.3c

> Use Firefox ESR (52) or Firefox 57

Can't use 57 (absolutely need a certain addon), I'll try 52 later.

**Comment by kkapsner** [comment] 2017-12-18 19:07
Hm... well I guess I have to install Firefox 56 then... maybe it can shine some light on the weird problems I currently have.

**Comment by kkapsner** [comment] 2017-12-18 19:09
Can you both please also answer the other questions above?

**Comment by kkapsner** [comment] 2017-12-18 23:33
Please try the version on the beta channel: https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta

**Comment by Joel889** [comment] 2017-12-19 05:42
> Please try the version on the beta channel: https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta

Seems to be working, although initially it was blocking all websites (didn't happen to me before). I had to enable and disable the extension and restart the browser in order for it to work.

**Comment by kkapsner** [comment] 2017-12-19 08:53
Thanks for checking.

The blocking is probably a combination with another addon. Which ones do you have installed? In which order did you install them?

If you see the blocking again, please set the logging level of CB to verbose and give me the content of the browser console (hit F12 in the not loading tab).

**Comment by licaon-kter** [comment] 2017-12-19 08:59
Seen something like this on FF52 on Android with 0.4.3c, after a while I'll get the dialogue about a bad script gone mad `Settings.js:613`

**Comment by Joel889** [comment] 2017-12-19 16:10
> can you reintroduce the blocking behaviour by uninstalling and reinstalling CB?
No, everything seems to be working now.

**Comment by kkapsner** [comment] 2017-12-19 22:12
Version 0.4.4 will be available soon - please check if everything is still working.

**Comment by licaon-kter** [comment] 2017-12-21 06:31
0.4.4b FF52 Android
While the AMO beta worked fine, this _stable_ version has issues again, in `settings.js:611` or `settings.js:618` or `logging.js:77`

**Comment by kkapsner** [comment] 2017-12-21 07:50
I will have a look.

**Comment by licaon-kter** [comment] 2017-12-21 13:36
More notes FF52 Android w/ 0.4.4b
* Opened several tabs, got the dialogue in the first ( `Settings.js:618` or `Logging.js:75` ) hit continue, nothing, all tabs stayed blank, hit reload to no avail.
* Killed browser, loaded one single tab, got dialogue, hit continue, page loaded
* Read a bit on that page, opened 2 links from it, scrolled around, now suddlenly everything except the part that was on screen   I opened the links turned blank. Open tabs stay blank.

**Comment by kkapsner** [comment] 2017-12-21 16:56
Can you reset the settings and then check again?
Can you try 0.4.4a?

**Comment by licaon-kter** [comment] 2017-12-21 17:03
I can't see the options, can I delete some keys in about:config? Which ones?

**Comment by kkapsner** [comment] 2017-12-21 20:06
No - there is nothing in about:config. Settings of WebExtensions work differently.

Ah... on Android the options page is not supported... well... it seem that Firefox 52 Android provides no option for WebExtensions to interact with the user. I will make a version that adds a bookmark to the settings page on Fennec. Let's see if that works.

**Comment by licaon-kter** [comment] 2017-12-21 20:57
FF52 supports WebExtensions?

**Comment by kkapsner** [comment] 2017-12-21 21:11
It better does... CB is a WebExtension since version 0.4.0.

**Comment by licaon-kter** [comment] 2017-12-22 07:26
After killing the browser, and clean cache, alpha20171219 worked pretty gfreat no dialogue even (my testing above was just after uninstalling alpha20171220 so not sure if some scripts might have been still loaded or something)

Now, 0.4.4a works ok too, no dialogue, pages load fast.

**Comment by kkapsner** [comment] 2017-12-22 08:06
Well - FF52 mobile does not even support bookmark creation... I starting to run out of ideas.

**Closed** 2017-12-22 08:07 UTC

**Comment by licaon-kter** [comment] 2017-12-22 08:49
> FF52 mobile does not even support bookmark creation
What do you mean?

So you'll target 0.4.4b to FF53 or later then? Else I'll have to disable extensions updates for all.

**Comment by kkapsner** [comment] 2017-12-22 15:13
I mean it does not support bookmark creation in a WebExtension. It does support for the normal user.

Unfortunately you have to disable update for CB at the moment. Some users will need 0.4.4b on FF 52.

**Comment by licaon-kter** [comment] 2017-12-23 11:05
I don't seem to have a way to control extensions updates per extension, either all or none (in about:config).

**Comment by kkapsner** [comment] 2017-12-23 15:16
As it seems this is a general problem on FF52 android I set the min version of 0.4.4b to 53.
So you should be able to enable updates.

**Comment by kkapsner** [comment] 2017-12-23 15:22
BTW: I'm currently working on #173. A small question: do you see the fingerprint symbol in the URL bar when something is faked (e.g. here on github)? And what does happen when you click on it?

**Comment by licaon-kter** [comment] 2017-12-23 15:51
First time I saw it, the fingerprint icon, was on FF57 Android.
I'll try to get some older versions and test.
