### ISSUE TITLE
UI pages are not responsive (Firefox Android friendly)

### ISSUE THREAD

**Issue by Riajyuu** [kkapsner/CanvasBlocker#387] opened 2019-07-25 01:34 UTC
## Description
Preset page on Firefox Android looks strange

## Expected Behavior
That page should be responsive

## Current Behavior
All layout is not resized properly

## Possible Solution
`<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1' />`

You may need more adjusting despite that line of meta

## Steps to Reproduce (for bugs)
1. Install CanvasBlocker 0.5.13 on Firefox Android
2. Open preset page

## Context
Irrelevant

## Your Environment
* CanvasBlocker Version used: 0.5.13
* Firefox version incl. 32- or 64-bit: Irrelevant
* Operating System and version (desktop or mobile): any of Firefox Android
* Installed addons: Irrelevant

## Your Settings
Irrelevant

---

Note that you don't have to use an Android to test. Simply use responsive design mode in Firefox 

![image](https://user-images.githubusercontent.com/16912240/61839507-63a19b00-aec0-11e9-87e5-2be142d74fc0.png)

**Comment by spodermenpls** [comment] 2019-07-25 03:08
I've just tested it with my phone, and can't confirm that issue. The preset page looks and works as intended on my end. 
The only negative I've noticed is "open in separate tab" being cropped away in its entirety (due to the narrow screen size), due to its alignment on the outter edge on the right hand side. Aligning it to the left would solve it, I think.. @kkapsner

**Comment by Riajyuu** [comment] 2019-07-25 03:11
> I've just tested it with my phone, and can't confirm that issue. The preset page looks and works as intended on my end.

![image](https://user-images.githubusercontent.com/16912240/61843049-e4ff2a80-aecc-11e9-8a94-d9c034ee2263.png)

Really? 😕

**Comment by spodermenpls** [comment] 2019-07-25 04:22
@Riajyuu It's the same as for the desktop version, so yes. There could be more strict line breaks for the descriptions though, so narrow screens would display it less zoomed-out.

**Comment by Riajyuu** [comment] 2019-07-25 04:57
> There could be stricter line breaks for the descriptions though, so narrow screens would display it less zoomed-out.

That's exactly how Web Devs define `non-responsive` 🙁

**Comment by spodermenpls** [comment] 2019-07-25 05:19
Well, CanvasBlocker happens to be "no-frills" when it comes to design extravaganza. 😅 How many times do you have to visit the settings preset page though? I assume not that often, so with the zoom/line break issue fixed, the site should be sufficient in my mind.

**Comment by kkapsner** [comment] 2019-07-25 14:37
@Riajyuu This is not how the preset page is supposed to look like on android (in the responsive design mode it looks like that: 
![grafik](https://user-images.githubusercontent.com/1105157/61883198-41c50a00-aefa-11e9-8c1a-43b16e5eb0e2.png)
But I do not have an Android device to test on the "real deal".

I think adding the meta tag should be enough.

**Comment by kkapsner** [comment] 2019-07-25 14:38
@spodermenpls the "open in separate tab" is only available on the options page when opened in about:addons.

**Comment by spodermenpls** [comment] 2019-07-25 18:38
This just replaces the need to zoom-in a lot with the need to scroll down a lot.. meh.

@kkapsner How else would I open the options page if not via "about:addons"? I've used that link many times before, it used to be there..

**Comment by kkapsner** [comment] 2019-07-25 20:22
If you click on the CB icon in the toolbar and search for something the options page opens in a separate tab. Also you could simply bookmark the URL.

Can you give me a screenshot of the case where the link is not usable.

**Comment by kkapsner** [comment] 2019-07-25 21:45
In an ideal world I would match the scaling so the content fills up the height of the screen. So the user sees everything and the can zoom in to the desired part.

**Comment by spodermenpls** [comment] 2019-07-26 01:09
I never use the search, that's why I didn't think of it. I've already recovered the link from my history and bookmarked it, but that's not an option for the majority of users who may be dealing with this, I suspect. My screen looks like this:

![Bildschirmfoto_20190726_001](https://user-images.githubusercontent.com/23747593/61918703-9ac08c80-af52-11e9-80b4-e65c0ed6f128.png)

**Comment by Riajyuu** [comment] 2019-07-26 01:19
@spodermenpls I suppose your screen is less than 720P while I have 1080P. That's how differences come.

And clearly that line of meta is not in any option page so that Firefox has to resize it as font size. Hence, uncomfortable scaling.

**Comment by KrasnayaPloshchad** [comment] 2019-07-26 15:23
This can be fixed with `@media` rules.

**Comment by spodermenpls** [comment] 2019-07-27 10:32
> I suppose your screen is less than 720P while I have 1080P.
Yes, my phone uses 540p.

**Comment by kkapsner** [comment] 2019-08-12 08:08
Well - both views are not how this is supposed to look like.

Seems that I have to do some design adjustments for android... yeah...

**Comment by KrasnayaPloshchad** [comment] 2019-08-13 09:36
For the settings page, the labels can be moved to the top with narrower screen.

**Comment by kkapsner** [comment] 2019-08-21 12:33
Please try the latest alpha: https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment] 2019-08-21 16:26
I like it - the settings sanitation and allowances still aren't responsive, though.

**Comment by kkapsner** [comment] 2019-08-22 07:17
You're right...

**Comment by Riajyuu** [comment] 2019-08-22 09:35
Hey. I just wanna to bright up that browserAction page needs this as well since ti is also a new tab on Android.

**Comment by kkapsner** [comment] 2019-09-11 22:12
Please try the latest beta version: https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment] 2019-09-15 23:33
Allowances, sanitation and toolbar menu look fine now too.

**Comment by kkapsner** [comment] 2019-09-16 09:14
Great. Thanks for checking.

**Closed by kkapsner** 2019-09-16 09:14 UTC
Labels: enhancement

**Comment by kkapsner** [comment] 2019-09-24 11:00
Version 0.5.14 is published.
