### ISSUE TITLE
Import not restore the persistentRndStorage section

### ISSUE THREAD

**Issue by hkfsc** [kkapsner/CanvasBlocker#618] opened 2022-05-08 20:46 UTC
I exported all settings included persistentRndStorage section and download the config file , but after import the config file I just downloaded, I just lost all persistentRndStorage section info...

## Expected Behavior
Restore all settings including persistentRndStorage part, for containers as well.

## Current Behavior
Lost all persistentRndStorage part info in the config file.

## Steps to Reproduce (for bugs)
1. Visit some canvas test websites(to let plugin generate the persistentRndStorage data)
2. Click Inspect to see if there is persistentRndStorage part, then export settings then check the downloaded file again.
3. Click clear button, then check with inspect again, persistentRndStorage  part should be empty now
4. Import the config file that we just exported and downloaded, check again.

## Your Environment

* CanvasBlocker Version used: 1.8
* Firefox version incl. 32- or 64-bit: 64 101.0
* Operating System and version (desktop or mobile): desktop
* Installed addons: CanvasBlocker

**Comment by kkapsner** [comment] 2022-05-12 22:29
I'm not able to reproduce the problem. Did you set "Store persistent data"?

**Comment by hkfsc** [comment] 2022-05-13 08:21
Yes

**Comment by kkapsner** [comment] 2022-05-14 08:15
Can you give me the exported settings file? Best would be all three states: the export, after clearing and after importing.

**Comment by kkapsner** [comment] 2022-07-11 20:16
No answer for almost two months -> I will close the issue. If the problem still exists and you can provide the files I can reopen it.

**Closed by kkapsner** 2022-07-11 20:16 UTC
