### ISSUE TITLE
New DomRect  Protecting Feature Is Breaking StartPage

### ISSUE THREAD

**Issue by Kraxys** [kkapsner/CanvasBlocker#270] opened 2018-09-24 05:15 UTC
## Description

When **Protect DomRect Api** is checked, no search result are displayed after launching a search on StartPage.
Of course a workaround could be to whitelist StartPage for this feature. But, except if StartPage is heavily relies on DomRect for displaying search results, making StartPage's page results entirely blank is maybe indicating  something is wrong in the way CB blocks DomRect.

## Your Environment

* CanvasBlocker Version used: 0.5.4
* Firefox 64-bit G0.2 ESR:
* Operating System and version (desktop or mobile): W7
* Installed addons: Only CB on the portable FF used to test

**Comment by kkapsner** [comment] 2018-09-24 07:00
I'm not able to reproduce your problem. The search results are shown. But it uses DOMRect quite extensively (170 times in my case).
Is there anything in the console?

**Comment by Kraxys** [comment] 2018-09-25 08:41
It's weird: I no more get this issue. Same browser used. I will perform further tests.

**Comment by Daniel-Kalus** [comment] 2018-09-25 11:51
I have the same issue with startpage when using both Block mode: "block readout API" and having Protect DOMRect API checked. Also these settings break the youtube player, it won't allow me to use the volume slider and clicking anywehere on the time bar just restarts the video.
Everything works fine using "fake readout API" or unchecking Protect DOMRect API on "block readout API"-mode.

**Comment by kkapsner** [comment] 2018-09-25 15:59
@Daniel-Kalus The "block readout API" is known to break things - so no surprise there.

**Comment by wesrt1** [comment] 2018-09-26 01:07
I'm using "fake readout API" and can confirm odd issues with StartPage, though I'm experiencing something a bit weirder.

I use a tiling window manager (awesome on ArchLinux) and every time a new window appears or I move a window, StartPage appears as if a newline is inserted after the first word in every search result description.

At first I thought it was an issue with StartPage related to window size changes (and that may very well be an underlying cause), but disabling DOMRect for startpage.com fixes it.

**Comment by kkapsner** [comment] 2018-09-27 05:50
Please test various values of "DOMRect integer factor" (8, 16, 32).

**Comment by kkapsner** [comment] 2018-09-27 13:12
I'm only able to reproduce the problem when I change the layout.css.devPixelsPerPx while the page is loaded.
But I have no clue what they are doing when this changes.

**Comment by kkapsner** [comment] 2018-10-03 21:02
Can you please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-Alpha3
With this I'm no longer able to reproduce the problem.

**Comment by kkapsner** [comment] 2018-10-07 11:10
Since I do not see the problem any more with the Alpha I will close this. When you still see it I can reopen it.

**Closed by kkapsner** 2018-10-07 11:10 UTC

**Comment by kkapsner** [comment] 2018-10-09 11:35
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC1

**Comment by kkapsner** [comment] 2018-10-13 10:41
Version 0.5.5 is out and ready to use.
