### ISSUE TITLE
Eats RAM for breakfast! (Memory leak of massive proportions)

### ISSUE THREAD

**Issue by TreeKittens** [kkapsner/CanvasBlocker#150] opened 2017-11-15 02:02 UTC
I have found that this plugin, in newer versions of Firefox (I first observed this behavior and attributed it to Canvas Blocker on Firefox version 56.0), has a pretty enormous memory leak, causing memory usage to jump up and down erratically with an overall climbing trend of megabytes per second--when I leave my browser unattended with CanvasBlocker enabled, it can reach upwards of 11 GB of memory usage for a tiny, few-kilobytes page (like html, head, title, /title, /head body, h1, /h1, /body /html is all that's in the page), causing computers with less memory to [thrash](https://en.wikipedia.org/wiki/Thrashing_(computer_science)) and thus completely destroying system performance.

When I observed this issue, I was using the most recent versions available: CanvasBlocker 0.4.2 on Firefox 56.0, Firefox build identifier Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0.

**Comment by kkapsner** [comment] 2017-11-15 12:17
I have a ton of tabs open and no RAM issues. Can you please update Firefox to the latest 56.0.2 (or even 57) and recheck? If the problem is still present please post your settings here (there is a new settings export button in the options page - you have to activate expert mode to see it).

**Comment by kkapsner** [comment] 2017-11-29 23:00
No answer = solved?
I close this issue. If you have more information and a reproduction scenario you can simply reopen it.

**Closed by kkapsner** 2017-11-29 23:00 UTC
