### ISSUE TITLE
about:blank page doesn't show

### ISSUE THREAD

**Issue by AnotherBugReporter** [kkapsner/CanvasBlocker#165] opened 2017-12-15 13:31 UTC
Open any page, then from there try to go to the about:blank page, for example by typing it the address bar. The address bar will correctly turn blank and the name tab will be the correct about:blank tab name but the page shown will not be blank, instead it will be the previous page still showing. After trying several times (number of retries needed varies), the page finally gets correctly blanked.
This happens since version 0.4.3b of CanvasBlocker, never before. Tried version 0.4.3a instead, exactly the same problem. Disabling this addon solves the problem. Disabling all addons but keeping only CanvasBlocker still shows the problem.
Configuration : Waterfox 56.0.1 x64 on windows 7.

**Comment by kkapsner** [comment] 2017-12-15 15:45
Everything fine when you back to 0.4.2?
Which plugins/addons are you using? Does the problem still persist when you are disabling all plugins?

PS: could be a 56 problem - never tested these version with 56. Only 52 (ESR), 57 (current) and 59 (nightly)

**Comment by AnotherBugReporter** [comment] 2017-12-15 16:32
Yes I tried to reinstall 0.4.2 and it didn't have the problem, problem is back with 0.4.3b installed.

I only have the flash plugin (but always disabled) and lots of extensions but as I said I made tests with all extensions disabled except CanvasBlocker and I still saw the problem, so I don't think it's a conflict, I'd prefer not to list them publicly if not absolutely necessary.

I tested with firefox 57.0.2 and CanvasBlocker 0.4.3b and didn't see the problem appear. So it seems waterfox-only, or maybe the issue would be here with firefox 56 too, I didn't test it.

Note that it's a minor problem as the extension still seems to work according to canvas fingerprinting tests (fake readout mode). It just seems strange and worries me that something deeper might be broken too. Note also that apparently waterfox 56 currently has some problems with extensions according to the author so the trouble might come entirely from waterfox...

**Comment by kkapsner** [comment] 2017-12-15 16:50
Forgot to mention you should save your setting before going back.

**Comment by kkapsner** [comment] 2017-12-15 18:18
At least I'm able to reproduce the problem. What's funny it that if you switch to a different tab and then back the page is cleared.

**Comment by kkapsner** [comment] 2017-12-15 19:08
Found the problem - will be fixed in the next version (seems to be 0.4.3c as we have problems with b...)

**Closed** 2017-12-15 19:07 UTC

**Comment by kkapsner** [comment] 2017-12-16 18:49
Release is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3c-Release
