### ISSUE TITLE
Window name protection breaks navigation on Protonmail

### ISSUE THREAD

**Issue by practik** [kkapsner/CanvasBlocker#243] opened 2018-09-04 18:34 UTC
## Description
With Window API protection enabled, it becomes impossible to navigate around the Protonmail interface by mouse, because every time you click on a link you get kicked back out to the login screen.

I tried whitelisting both `protonmail.com` and `^https://mail\.protonmail\.com/.*$`, but neither worked.

The only thing that has worked for me so far is to whitelist the name part of the Window API, but a domain-specific exception would be preferable. (Some guidelines for how to add site-specific settings would also be helpful for people like me who aren't regex masters.)

## Your Environment
* CanvasBlocker Version used: 0.5.3
* Firefox version incl. 32- or 64-bit: 61.0.2 (64-bit)
* Operating System and version (desktop or mobile): macOS 10.12.6
* Installed addons:
```
Name 	Version 	Enabled 	ID
CanvasBlocker	0.5.3	true	CanvasBlocker@kkapsner.de
Cookie Quick Manager	0.3rc3	true	{60f82f00-9ad5-4de5-b31c-b16a47c51558}
CSS Exfil Protection	1.0.8	true	{7fc8ef53-24ec-4205-87a4-1e745953bb0d}
Decentraleyes	2.0.6	true	jid1-BoFifL9Vbdl2zQ@jetpack
Download Cleaner Lite	1.3	true	download-cleaner-lite@futuretech.in
Forget Me Not - Forget cookies & other data	1.0.5	true	forget-me-not@lusito.info
Greasemonkey	4.7	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HTTPS Everywhere	2018.8.22	true	https-everywhere@eff.org
Kiwix	2.3.0	true	kiwix-html5-listed@kiwix.org
Select After Closing Current	3.1	true	select-after-closing-current@qw.linux-2g64.local
uBlock Origin	1.16.20	true	uBlock0@raymondhill.net
Video DownloadHelper	7.3.5	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Cookie AutoDelete	2.2.0	false	CookieAutoDelete@kennydo.com
```

## Your Settings
```
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": true
		}
	],
	"hiddenSettings": {
		"protectAudio": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 100000,
	"rng": "persistent",
	"apiWhiteList": {
		"name": true
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1511998281129,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "18",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"blockDataURLs": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}
```

**Comment by kkapsner** [comment] 2018-09-04 18:45
Hm... I'm not able to reproduce your problem. And I do not understand why whitelisting did not work...

But this url specific setting should work for you:
![grafik](https://user-images.githubusercontent.com/1105157/45051102-5a7ac600-b083-11e8-8d3f-561bb570916d.png)

**Comment by practik** [comment] 2018-09-04 19:37
Huh. I was sure my site-specific settings were bad. But now, after disabling all my other extensions and turning them back on again one by one … now I can't reproduce the problem either. ??? Sorry to bother you, and thank you for responding so quickly!

**Comment by kkapsner** [comment] 2018-09-04 19:46
No problem.
Maybe it was the order of the extensions...

**Comment by Maryse47** [comment] 2018-09-05 11:53
I have similar problem. Whitelist isn't honored for WindowAPI. I added ip-check.info but it's still blocked on http://ip-check.info/?lang=en

**Comment by kkapsner** [comment] 2018-09-05 14:13
I will have a look at this.

**Comment by kkapsner** [comment] 2018-09-05 14:20
I'm not able to reproduce the problem. How did you whitelist it? What are your settings?

**Comment by Maryse47** [comment] 2018-09-05 19:00
I simply add `ip-check.info` to window api whitelist. It works with fresh profile however after page refresh the ui claims that window api is blocked while it's not which is confusing. I tried to disable some addons in my main profile but that didn't help. Feel free to close this as it may be something specific to my config.

**Comment by kkapsner** [comment] 2018-09-05 20:04
What do you mean by "window api whitelist"? There is only one whitelist which is API independent.
Do you mean the normal whitelist?
![grafik](https://user-images.githubusercontent.com/1105157/45118077-a5fea400-b157-11e8-801b-6abd1fee81e2.png)


Which domain is displayed if you open the notification popup: 
![grafik](https://user-images.githubusercontent.com/1105157/45116322-a6e10700-b152-11e8-8ef9-ffa8c8999ee1.png)

**Comment by Maryse47** [comment] 2018-09-05 21:53
> What do you mean by "window api whitelist"

I meant "site specific settings" under "Window API" like in your screenshot at https://github.com/kkapsner/CanvasBlocker/issues/243#issuecomment-418476285

It seems that I misunderstood the UI (perhaps I'm still don't get everything). I thought that "site specific settings" under "Window API" works like whitelist if I add entry and tick the box next to it. (I still don't know what ticking/unticking the box mean).

Now AFAIK the actual behavior is controlled from "Block mode" "site specific settings". I had "block readout API" chosen as default and didn't overrode it for `ip-check.info` which was always breaking that site in result. If I change the default or "site specific settings" to "fake readout API" it's correctly applied.

Do this mean that I can't control site behavior separately for API? What I wanted is to change "Window API" behavior for specific domain/rule and leave Canvas with default option for "Block mode".

Sorry for my initial confusion and thank you for patience.

**Comment by kkapsner** [comment] 2018-09-05 21:58
Ah... this site specific settings mean that the setting can be set for that specific RegExp/domain.
You should uncheck the site specific box if you want the window API protected but want to add an exception.

**Comment by kkapsner** [comment] 2018-09-05 22:02
But you are right: the block mode is not API specific. If you block you block all APIs. And I will not change that.

**Closed by kkapsner** 2018-09-05 22:02 UTC

**Comment by Maryse47** [comment] 2018-09-05 22:07
> You should uncheck the site specific box if you want the window API protected but want to add an exception

What checking that box mean?

> But you are right: the block mode is not API specific. If you block you block all APIs. And I will not change that.

My concern is that when I want to unblock specific domain for Window API it unblocks Canvas at the same time.

**Comment by kkapsner** [comment] 2018-09-05 22:18
Checking that box means, that this setting should be set for this domain/RegExp.

You want the window API to be protected. That's why you checked the the main box -> the setting is on
Now you want to add an exception and add a site specific entry. You want this setting to be off for this site therefore you have to uncheck the site specific box -> the setting is off for the entry.

It's the same principle as for the block mode. But in this case it's an on/off setting and not a choice.

> My concern is that when I want to unblock specific domain for Window API it unblocks Canvas at the same time.

I see your point, but I think the fake mode is actually the better mode. It's breaks way less pages and is not as detectable as the block mode. So better for privacy and better for usability -> win-win.

**Comment by Maryse47** [comment] 2018-09-05 22:47
I noticed that when I set "block readout API" in "Block mode" then it blocks "Window API even when main "Protect window API" box is unchecked.  The only way to unblock "Window API" is to add it to "API whitelist". This doesn't happen when I set  "Block mode" to "fake readout API." The "Window API" is ignored (not faked) when main "Protect window API" box is unchecked and faked when main "Protect window API" box is checked. This looks like a bug.

> I see your point, but I think the fake mode is actually the better mode. It's breaks way less pages and is not as detectable as the block mode. So better for privacy and better for usability -> win-win.

It doesn't matter if global option is set to Block or Fake mode. The issue is that site override for "Window API" is override for "Canvas" at the same time. I.E. having global fake mode and want to set "allow everything" for "Window API" you "allow everything" for "Canvas" as well.

**Comment by Maryse47** [comment] 2018-09-05 23:29
Another thing, when I set "Block mode" to "fake readout API", check main "Protect window API" and uncheck "site specific settings" box for domain then the "Window API" is ignored for that domain (should be faked). If I change "Block mode" "site specific settings" for that domain to "block readout API" then "Window API" is correctly blocked.

**Comment by Maryse47** [comment] 2018-09-05 23:45
I think the "Window API" site specific settings should be controlled from one place/list, i.e get rid of checkboxes and show domains like under  "Block mode". Otherwise there are too many possible combinations.

**Comment by Maryse47** [comment] 2018-09-06 18:28
> I think I do not quite understand your problem. What do you exactly want to accomplish?

Nothing. I just thought the UI can be simplified. The inconsistency between block/fake mode was a major headache but I see it's fixed now. I'll test it after new release and report back if I spot any other issues. Thank you again for this great work.

**Comment by kkapsner** [comment] 2018-09-06 18:32
I'm sure the UI can be simplified. I just do not know how... 

If want you can test with https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha1
But be aware that the beta has a different ID and is therefore a separate addon. You should disable the normal one first.

**Comment by kkapsner** [comment] 2018-09-19 17:19
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC1

**Comment by kkapsner** [comment] 2018-09-23 11:14
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4

**Comment by Maryse47** [comment] 2018-09-23 17:31
It seems working great, I don't have anything to report as for now. Thanks!

**Comment by kkapsner** [comment] 2018-09-23 17:58
You're welcome.
